import 'server-only';
import { NextRequest, NextResponse } from 'next/server';
import PDFDocument from 'pdfkit';
import { createClient as createSSRClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { canReleaseEvaluationRead } from '@/lib/jobs/readReleaseGate';
import { isEvaluationResultV1, type EvaluationResultV1 } from '@/schemas/evaluation-result-v1';
import { isEvaluationResultV2, type EvaluationResultV2 } from '@/schemas/evaluation-result-v2';
import type { LongformDreamDocument } from '@/lib/evaluation/pipeline/runPass3bLongform';
import { AlignmentType, Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const LONG_FORM_WORD_THRESHOLD = 25000;
const WORDS_PER_MANUSCRIPT_PAGE = 250;
const EXPORT_DISCLAIMER =
  'Generated by RevisionGrade™. Author retains ownership of manuscript content. This report is an editorial diagnostic and does not guarantee publication, representation, or commercial outcome.';

const BRAND = {
  ink: '#0E0E0E',
  charcoal: '#16120D',
  panel: '#1F1A13',
  gold: '#A98E4A',
  goldSoft: '#D8C58A',
  cream: '#F2EFEA',
  cream2: '#C8BFB0',
  paper: '#FBF8F1',
  paper2: '#F4EFE5',
  text: '#1F2937',
  muted: '#6B6256',
  rule: '#D8C9A3',
  oxblood: '#7A1E1E',
} as const;

const DOCX = {
  ink: '0E0E0E',
  gold: 'A98E4A',
  cream2: '6B6256',
  text: '1F2937',
  oxblood: '7A1E1E',
} as const;

type ExportFormat = 'pdf' | 'docx' | 'txt';
type ExportableResult = EvaluationResultV1 | EvaluationResultV2;

type ExportableResultShape = {
  generated_at?: unknown;
  schema_version?: unknown;
  metrics?: { manuscript?: { title?: unknown; word_count?: unknown; genre?: unknown } };
  overview?: {
    verdict?: unknown;
    overall_score_0_100?: unknown;
    one_paragraph_summary?: unknown;
    top_3_strengths?: unknown;
    top_3_risks?: unknown;
  };
  criteria?: unknown;
  recommendations?: {
    quick_wins?: unknown;
    strategic_revisions?: unknown;
  };
};

type ReportMetadata = {
  displayTitle: string;
  generatedAt: string;
  score: string;
  verdict: string;
  wordCount: number | null;
  estimatedPages: number | null;
  reportType: string;
  shelf: string | null;
  genre: string | null;
};

function isExportableResultCandidate(value: unknown): value is ExportableResult {
  if (isEvaluationResultV1(value) || isEvaluationResultV2(value)) return true;

  if (!value || typeof value !== 'object') return false;

  const candidate = value as ExportableResultShape;
  return (
    typeof candidate.generated_at === 'string' &&
    typeof candidate.overview?.verdict === 'string' &&
    typeof candidate.overview?.one_paragraph_summary === 'string' &&
    Array.isArray(candidate.overview?.top_3_strengths) &&
    Array.isArray(candidate.overview?.top_3_risks) &&
    Array.isArray(candidate.criteria) &&
    Array.isArray(candidate.recommendations?.quick_wins) &&
    Array.isArray(candidate.recommendations?.strategic_revisions)
  );
}

function safeFilename(title: string | null, jobId: string, ext: string): string {
  const base = title ? title.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 40) : jobId.slice(0, 8);
  return `revision-grade-${base}.${ext}`;
}

function extractManuscriptTitle(manuscripts: unknown): string | null {
  const relation = Array.isArray(manuscripts) ? manuscripts[0] : manuscripts;
  const title =
    typeof relation === 'object' && relation && 'title' in relation
      ? (relation as { title?: unknown }).title
      : null;
  return typeof title === 'string' && title.trim().length > 0 ? title.trim() : null;
}

function asText(value: unknown): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null;
}

function scoreLabel(score: number | null | undefined, denominator: number): string {
  return typeof score === 'number' ? `${Math.round(score)}/${denominator}` : `—/${denominator}`;
}

function estimatePages(wordCount: number | null): number | null {
  if (typeof wordCount !== 'number' || !Number.isFinite(wordCount) || wordCount <= 0) return null;
  return Math.max(1, Math.ceil(wordCount / WORDS_PER_MANUSCRIPT_PAGE));
}

function inferReportType(wordCount: number | null): string {
  if (typeof wordCount !== 'number' || !Number.isFinite(wordCount)) return 'Evaluation Report';
  return wordCount >= LONG_FORM_WORD_THRESHOLD ? 'Long-form Evaluation Report' : 'Short-form Evaluation Report';
}

function stripMachineResidue(text: string): string {
  return text
    .replace(/\bindirect_speech\b/g, 'indirect speech')
    .replace(/\breported_speech\b/g, 'reported speech')
    .replace(/\btagged_speech\b/g, 'tagged speech')
    .replace(/\baction_beat_attribution\b/g, 'action-beat attribution')
    .replace(/\s+/g, ' ')
    .trim();
}

function looksTruncated(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) return true;
  if (/\blean on extend\.?$/i.test(trimmed)) return true;
  if (/\b(?:and|or|but|while|because|although|through|with|to|from|into|across|between|including|against)$/i.test(trimmed)) return true;
  return trimmed.length > 120 && !/[.!?”’)]$/.test(trimmed);
}

function buildSummaryFallback(result: ExportableResult): string {
  const strengths = result.overview.top_3_strengths.map(stripMachineResidue).filter(Boolean);
  const risks = result.overview.top_3_risks.map(stripMachineResidue).filter(Boolean);
  const strengthSentence = strengths.length
    ? `The strongest areas are ${strengths.slice(0, 2).join(' ')}`
    : 'The strongest areas are detailed in the criteria analysis.';
  const riskSentence = risks.length
    ? `The primary risks are ${risks.slice(0, 2).join(' ')}`
    : 'The primary risks are detailed in the criteria analysis.';
  return `${strengthSentence} ${riskSentence}`;
}

function cleanReportText(text: unknown, fallback = '—', options: { blockTruncation?: boolean } = {}): string {
  const raw = asText(text);
  if (!raw) return fallback;
  const cleaned = stripMachineResidue(raw);
  if (options.blockTruncation && looksTruncated(cleaned)) return fallback;
  return cleaned;
}

function splitReportParagraphs(text: string): string[] {
  const cleaned = text.replace(/\s+/g, ' ').trim();
  if (!cleaned) return [];
  if (cleaned.length <= 760) return [cleaned];

  const sentences = cleaned.match(/[^.!?]+[.!?”’)]*/g)?.map((s) => s.trim()).filter(Boolean) ?? [cleaned];
  const paragraphs: string[] = [];
  let buffer = '';

  for (const sentence of sentences) {
    const next = buffer ? `${buffer} ${sentence}` : sentence;
    if (next.length > 520 && buffer) {
      paragraphs.push(buffer);
      buffer = sentence;
    } else {
      buffer = next;
    }
  }

  if (buffer) paragraphs.push(buffer);
  return paragraphs.length ? paragraphs : [cleaned];
}

function buildMetadata(result: ExportableResult, title: string | null, dream: LongformDreamDocument | null): ReportMetadata {
  const wordCount = typeof result.metrics?.manuscript?.word_count === 'number' ? result.metrics.manuscript.word_count : null;
  const displayTitle = title ?? result.metrics?.manuscript?.title ?? 'Untitled Manuscript';
  const shelf = dream?.market_shelf?.best_shelf ?? null;
  const genre = result.metrics?.manuscript?.genre ?? null;
  return {
    displayTitle,
    generatedAt: result.generated_at,
    score: scoreLabel(result.overview.overall_score_0_100, 100),
    verdict: result.overview.verdict.toUpperCase(),
    wordCount,
    estimatedPages: estimatePages(wordCount),
    reportType: inferReportType(wordCount),
    shelf,
    genre: genre ?? null,
  };
}

function pushTextParagraphs(lines: string[], text: unknown, prefix = ''): void {
  splitReportParagraphs(cleanReportText(text)).forEach((paragraph, index) => {
    lines.push(`${prefix}${paragraph}`);
    if (index < splitReportParagraphs(cleanReportText(text)).length - 1) lines.push('');
  });
}

function appendDreamTxtSections(lines: string[], dream: LongformDreamDocument): void {
  const sep = '='.repeat(72);
  const sub = '-'.repeat(72);
  const push = (s: string) => lines.push(s);

  push('');
  push(sep);
  push('NARRATIVE SYNTHESIS — HOLISTIC CRAFT ASSESSMENT');
  push(sep);
  push('');
  push(`Quality: ${dream.dream_scores?.quality ?? '—'}/100`);
  push(`Readiness: ${dream.dream_scores?.readiness ?? '—'}/100`);
  push(`Commercial: ${dream.dream_scores?.commercial ?? '—'}/100`);
  push(`Literary: ${dream.dream_scores?.literary ?? '—'}/100`);
  push('');
  push('Executive Verdict:');
  pushTextParagraphs(lines, dream.executive_verdict);

  if (dream.market_shelf) {
    push('');
    push(sub);
    push('MARKET SHELF');
    push(sub);
    push(`Best shelf: ${cleanReportText(dream.market_shelf.best_shelf)}`);
    push(`Marketable hook: ${cleanReportText(dream.market_shelf.marketable_hook)}`);
    if (Array.isArray(dream.market_shelf.shelf_neighbors) && dream.market_shelf.shelf_neighbors.length > 0) {
      push('Shelf neighbors:');
      dream.market_shelf.shelf_neighbors.forEach((item) => push(`  • ${cleanReportText(item)}`));
    }
    if (Array.isArray(dream.market_shelf.comparison_space) && dream.market_shelf.comparison_space.length > 0) {
      push('Comparison space:');
      dream.market_shelf.comparison_space.forEach((item) => push(`  • ${cleanReportText(item)}`));
    }
    push(`Market danger: ${cleanReportText(dream.market_shelf.market_danger)}`);
  }

  if (Array.isArray(dream.structural_stack) && dream.structural_stack.length > 0) {
    push('');
    push(sub);
    push('STRUCTURAL STACK');
    push(sub);
    dream.structural_stack.forEach((layer) => {
      push('');
      push(`${cleanReportText(layer.layer_name)} — ${layer.status}`);
      push('');
      pushTextParagraphs(lines, `Function: ${cleanReportText(layer.function)}`, '  ');
      pushTextParagraphs(lines, `Revision note: ${cleanReportText(layer.revision_note)}`, '  ');
    });
  }

  if (Array.isArray(dream.arc_map) && dream.arc_map.length > 0) {
    push('');
    push(sub);
    push('ARC MAP');
    push(sub);
    dream.arc_map.forEach((act) => {
      push('');
      push(`${cleanReportText(act.act_name)} (${cleanReportText(act.chapter_range)})`);
      push('');
      pushTextParagraphs(lines, `Function: ${cleanReportText(act.primary_function)}`, '  ');
      pushTextParagraphs(lines, `Revision priority: ${cleanReportText(act.revision_priority)}`, '  ');
    });
  }

  if (Array.isArray(dream.criterion_analyses) && dream.criterion_analyses.length > 0) {
    push('');
    push(sub);
    push('EXPANDED CRITERION ANALYSIS');
    push(sub);
    dream.criterion_analyses.forEach((a) => {
      push('');
      push(`${a.key} — ${a.score}/10 (${a.confidence} confidence)`);
      if (Array.isArray(a.fit_evidence) && a.fit_evidence.length > 0) pushTextParagraphs(lines, `What is working: ${a.fit_evidence.map((item) => cleanReportText(item)).join('; ')}`, '  ');
      if (Array.isArray(a.gap_evidence) && a.gap_evidence.length > 0) pushTextParagraphs(lines, `What weakens impact: ${a.gap_evidence.map((item) => cleanReportText(item)).join('; ')}`, '  ');
      if (Array.isArray(a.revision_queue) && a.revision_queue.length > 0) pushTextParagraphs(lines, `Revision queue: ${a.revision_queue.map((item) => cleanReportText(item)).join('; ')}`, '  ');
    });
  }

  if (Array.isArray(dream.revision_plan) && dream.revision_plan.length > 0) {
    push('');
    push(sub);
    push('REVISION PLAN');
    push(sub);
    dream.revision_plan.forEach((item) => {
      push('');
      push(`Priority ${item.priority}: ${cleanReportText(item.title)}`);
      pushTextParagraphs(lines, `Goal: ${cleanReportText(item.goal)}`, '  ');
      if (Array.isArray(item.actions) && item.actions.length > 0) pushTextParagraphs(lines, `Actions: ${item.actions.map((action) => cleanReportText(action)).join('; ')}`, '  ');
      if (item.acceptance_check) pushTextParagraphs(lines, `Acceptance check: ${cleanReportText(item.acceptance_check)}`, '  ');
    });
  }
}

function buildTxtReport(result: ExportableResult, title: string | null, jobId: string, dream: LongformDreamDocument | null): string {
  const lines: string[] = [];
  const sep = '='.repeat(76);
  const sub = '-'.repeat(76);
  const metadata = buildMetadata(result, title, dream);
  const summaryFallback = buildSummaryFallback(result);

  lines.push(sep);
  lines.push('REVISIONGRADE™ EVALUATION REPORT');
  lines.push('Professional manuscript diagnostic export');
  lines.push(sep);
  lines.push(`Manuscript Title: ${metadata.displayTitle}`);
  lines.push(`Report Type: ${metadata.reportType}`);
  if (metadata.genre) lines.push(`Genre: ${metadata.genre}`);
  if (metadata.shelf) lines.push(`Shelf: ${metadata.shelf}`);
  if (metadata.wordCount) lines.push(`Submitted Word Count: ${metadata.wordCount.toLocaleString()}`);
  if (metadata.estimatedPages) lines.push(`Estimated Manuscript Pages: ${metadata.estimatedPages.toLocaleString()} at ${WORDS_PER_MANUSCRIPT_PAGE} words/page`);
  lines.push(`Generated: ${metadata.generatedAt}`);
  lines.push(`Overall Score: ${metadata.score}`);
  lines.push(`Verdict: ${metadata.verdict}`);
  lines.push('Confidentiality: Prepared for author/editorial use.');
  lines.push('');

  lines.push(sub);
  lines.push('SUMMARY');
  lines.push(sub);
  pushTextParagraphs(lines, cleanReportText(result.overview.one_paragraph_summary, summaryFallback, { blockTruncation: true }));
  lines.push('');

  lines.push(sub);
  lines.push('TOP STRENGTHS');
  lines.push(sub);
  result.overview.top_3_strengths.forEach((s, i) => lines.push(`${i + 1}. ${cleanReportText(s)}`));
  lines.push('');

  lines.push(sub);
  lines.push('TOP RISKS');
  lines.push(sub);
  result.overview.top_3_risks.forEach((r, i) => lines.push(`${i + 1}. ${cleanReportText(r)}`));
  lines.push('');

  lines.push(sub);
  lines.push('CRITERIA SCORES');
  lines.push(sub);
  result.criteria.forEach((c) => {
    lines.push(`• ${c.key} — ${scoreLabel(c.score_0_10, 10)}${c.confidence_level ? ` (${c.confidence_level} confidence)` : ''}`);
    if (c.rationale) {
      lines.push('');
      pushTextParagraphs(lines, `Rationale: ${cleanReportText(c.rationale)}`, '  ');
    }
    lines.push('');
  });

  lines.push(sub);
  lines.push('QUICK WINS');
  lines.push(sub);
  if (result.recommendations.quick_wins.length === 0) lines.push('(none)');
  result.recommendations.quick_wins.forEach((qw, i) => {
    lines.push(`${i + 1}. ${cleanReportText(qw.action)} [effort: ${qw.effort}, impact: ${qw.impact}]`);
    if (qw.why) pushTextParagraphs(lines, `Why: ${cleanReportText(qw.why)}`, '   ');
  });
  lines.push('');

  lines.push(sub);
  lines.push('STRATEGIC REVISIONS');
  lines.push(sub);
  if (result.recommendations.strategic_revisions.length === 0) lines.push('(none)');
  result.recommendations.strategic_revisions.forEach((sr, i) => {
    lines.push(`${i + 1}. ${cleanReportText(sr.action)} [effort: ${sr.effort}, impact: ${sr.impact}]`);
    if (sr.why) pushTextParagraphs(lines, `Why: ${cleanReportText(sr.why)}`, '   ');
  });

  if (dream) appendDreamTxtSections(lines, dream);

  lines.push('');
  lines.push(sub);
  lines.push('TECHNICAL METADATA');
  lines.push(sub);
  lines.push(`Job ID: ${jobId}`);
  lines.push(`Schema: ${result.schema_version}`);
  lines.push('');
  lines.push(sep);
  lines.push(EXPORT_DISCLAIMER);
  return lines.join('\n');
}

async function buildPdfReport(result: ExportableResult, title: string | null, jobId: string, dream: LongformDreamDocument | null): Promise<Buffer> {
  return await new Promise<Buffer>((resolve, reject) => {
    const metadata = buildMetadata(result, title, dream);
    const summaryFallback = buildSummaryFallback(result);
    const doc = new PDFDocument({ size: 'LETTER', margin: 54, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer | Uint8Array) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const contentWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const bottomY = () => doc.page.height - doc.page.margins.bottom - 44;
    let interiorMode = false;

    const drawInteriorBackground = () => {
      doc.save();
      doc.rect(0, 0, doc.page.width, doc.page.height).fill(BRAND.paper);
      doc.rect(0, 0, doc.page.width, 36).fill(BRAND.ink);
      doc.font('Helvetica-Bold').fontSize(7).fillColor(BRAND.gold).text('REVISIONGRADE™', doc.page.margins.left, 13, { characterSpacing: 1.2 });
      doc.font('Helvetica').fontSize(6.5).fillColor(BRAND.cream2).text('CONFIDENTIAL MANUSCRIPT DIAGNOSTIC', doc.page.margins.left + 92, 13, { characterSpacing: 1.1 });
      doc.restore();
    };

    doc.on('pageAdded', () => {
      if (interiorMode) drawInteriorBackground();
    });

    const addInteriorPage = () => {
      interiorMode = true;
      doc.addPage();
    };

    const ensureSpace = (height = 90) => {
      if (doc.y + height > bottomY()) addInteriorPage();
    };

    const section = (text: string) => {
      ensureSpace(84);
      doc.moveDown(1.05);
      doc.font('Helvetica-Bold').fontSize(8).fillColor(BRAND.gold).text(text.toUpperCase(), {
        width: contentWidth,
        characterSpacing: 1.6,
      });
      doc.moveDown(0.35);
      doc.moveTo(doc.page.margins.left, doc.y).lineTo(doc.page.margins.left + contentWidth, doc.y).strokeColor(BRAND.rule).lineWidth(0.75).stroke();
      doc.strokeColor('#000000').lineWidth(1);
      doc.moveDown(0.75);
    };

    const subhead = (text: string, meta?: string) => {
      ensureSpace(58);
      doc.font('Helvetica-Bold').fontSize(11).fillColor(BRAND.text).text(cleanReportText(text), { width: contentWidth });
      if (meta) doc.font('Helvetica').fontSize(8.5).fillColor(BRAND.muted).text(meta, { width: contentWidth });
      doc.moveDown(0.35);
    };

    const paragraph = (text: string) => {
      const paragraphs = splitReportParagraphs(cleanReportText(text));
      paragraphs.forEach((part) => {
        ensureSpace(72);
        doc.font('Helvetica').fontSize(10.35).fillColor(BRAND.text).text(part, {
          width: contentWidth,
          lineGap: 4.25,
        });
        doc.moveDown(0.78);
      });
    };

    const bullet = (text: string) => {
      ensureSpace(50);
      doc.font('Helvetica').fontSize(10.25).fillColor(BRAND.text).text(`• ${cleanReportText(text)}`, {
        width: contentWidth,
        indent: 12,
        lineGap: 3.6,
      });
      doc.moveDown(0.42);
    };

    const labelValue = (label: string, value: string | null) => {
      if (!value) return;
      ensureSpace(36);
      doc.font('Helvetica-Bold').fontSize(8.2).fillColor(BRAND.gold).text(label.toUpperCase(), { continued: true, characterSpacing: 1.1 });
      doc.font('Helvetica').fontSize(9.5).fillColor(BRAND.text).text(`  ${value}`, { width: contentWidth });
      doc.moveDown(0.35);
    };

    const coverMeta = (label: string, value: string | null, x: number, y: number, w: number, h: number) => {
      if (!value) return;
      doc.roundedRect(x, y, w, h, 8).fillAndStroke(BRAND.panel, BRAND.gold);
      doc.font('Helvetica-Bold').fontSize(6.8).fillColor(BRAND.gold).text(label.toUpperCase(), x + 14, y + 12, {
        width: w - 28,
        characterSpacing: 1.25,
      });
      doc.font('Helvetica').fontSize(11.2).fillColor(BRAND.cream).text(value, x + 14, y + 27, {
        width: w - 28,
        lineGap: 1.5,
      });
    };

    // Cover page: premium, shareable artifact.
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(BRAND.ink);
    doc.rect(0, 0, doc.page.width, 12).fill(BRAND.gold);
    doc.rect(54, 72, 4, doc.page.height - 144).fill(BRAND.gold);
    doc.roundedRect(78, 72, 36, 36, 3).strokeColor(BRAND.gold).lineWidth(1).stroke();
    doc.font('Helvetica-Bold').fontSize(16).fillColor(BRAND.gold).text('R', 91, 82);
    doc.font('Helvetica-Bold').fontSize(9).fillColor(BRAND.gold).text('REVISIONGRADE™', 132, 76, { characterSpacing: 1.6 });
    doc.font('Helvetica').fontSize(8.5).fillColor(BRAND.cream2).text('CONFIDENTIAL MANUSCRIPT DIAGNOSTIC', 132, 94, { characterSpacing: 1.15 });

    doc.font('Helvetica-Bold').fontSize(36).fillColor(BRAND.cream).text('Evaluation Report', 78, 150, {
      width: doc.page.width - 156,
      lineGap: 2,
    });
    doc.moveDown(0.25);
    doc.font('Helvetica').fontSize(17).fillColor(BRAND.goldSoft).text(metadata.displayTitle, {
      width: doc.page.width - 156,
      lineGap: 3,
    });

    doc.moveTo(78, 258).lineTo(doc.page.width - 78, 258).strokeColor(BRAND.gold).lineWidth(0.7).stroke();

    const cardW = (doc.page.width - 168) / 2;
    const cardH = 56;
    const leftX = 78;
    const rightX = leftX + cardW + 12;
    let cardY = 292;
    coverMeta('Report Type', metadata.reportType, leftX, cardY, cardW, cardH);
    coverMeta('Overall Score', metadata.score, rightX, cardY, cardW, cardH);
    cardY += cardH + 12;
    coverMeta('Verdict', metadata.verdict, leftX, cardY, cardW, cardH);
    coverMeta('Generated', metadata.generatedAt, rightX, cardY, cardW, cardH);
    cardY += cardH + 12;
    coverMeta('Word Count', metadata.wordCount ? metadata.wordCount.toLocaleString() : null, leftX, cardY, cardW, cardH);
    coverMeta('Estimated Pages', metadata.estimatedPages ? `${metadata.estimatedPages.toLocaleString()} at ${WORDS_PER_MANUSCRIPT_PAGE} words/page` : null, rightX, cardY, cardW, cardH);
    cardY += cardH + 12;
    coverMeta('Genre', metadata.genre, leftX, cardY, cardW, cardH);
    coverMeta('Shelf', metadata.shelf, rightX, cardY, cardW, cardH);

    doc.roundedRect(78, 622, doc.page.width - 156, 66, 10).fill(BRAND.charcoal);
    doc.font('Helvetica-Bold').fontSize(7.8).fillColor(BRAND.gold).text('PREPARED FOR AUTHOR / EDITORIAL USE', 96, 640, { characterSpacing: 1.25 });
    doc.font('Helvetica').fontSize(9.25).fillColor(BRAND.cream2).text(
      'This report is designed to be shared as a professional manuscript-readiness artifact. It omits dashboard controls, app chrome, and internal workflow clutter.',
      96,
      657,
      { width: doc.page.width - 192, lineGap: 2.5 },
    );
    doc.font('Helvetica').fontSize(7.5).fillColor(BRAND.cream2).text(
      'Powered by RevisionGrade™ · Author retains ownership of manuscript content.',
      78,
      doc.page.height - 70,
      { width: doc.page.width - 156, align: 'center' },
    );

    addInteriorPage();

    section('Summary');
    paragraph(cleanReportText(result.overview.one_paragraph_summary, summaryFallback, { blockTruncation: true }));

    section('Top Strengths');
    result.overview.top_3_strengths.length ? result.overview.top_3_strengths.forEach(bullet) : paragraph('(none)');

    section('Top Risks');
    result.overview.top_3_risks.length ? result.overview.top_3_risks.forEach(bullet) : paragraph('(none)');

    section('Criteria Scores');
    result.criteria.forEach((c) => {
      ensureSpace(110);
      doc.roundedRect(doc.page.margins.left - 8, doc.y - 4, contentWidth + 16, 28, 6).fillAndStroke(BRAND.paper2, BRAND.rule);
      doc.font('Helvetica-Bold').fontSize(10.7).fillColor(BRAND.text).text(
        `${c.key} — ${scoreLabel(c.score_0_10, 10)}`,
        doc.page.margins.left,
        doc.y + 4,
        { width: contentWidth * 0.58 },
      );
      if (c.confidence_level) {
        doc.font('Helvetica-Bold').fontSize(7.6).fillColor(BRAND.gold).text(
          `${c.confidence_level} confidence`.toUpperCase(),
          doc.page.margins.left + contentWidth * 0.62,
          doc.y - 12,
          { width: contentWidth * 0.38, align: 'right', characterSpacing: 1.0 },
        );
      }
      doc.y += 22;
      if (c.rationale) paragraph(cleanReportText(c.rationale));
    });

    section('Quick Wins');
    result.recommendations.quick_wins.length ? result.recommendations.quick_wins.forEach((qw, idx) => {
      subhead(`${idx + 1}. ${cleanReportText(qw.action)}`, `Effort: ${qw.effort} · Impact: ${qw.impact}`);
      if (qw.why) paragraph(cleanReportText(qw.why));
    }) : paragraph('(none)');

    section('Strategic Revisions');
    result.recommendations.strategic_revisions.length ? result.recommendations.strategic_revisions.forEach((sr, idx) => {
      subhead(`${idx + 1}. ${cleanReportText(sr.action)}`, `Effort: ${sr.effort} · Impact: ${sr.impact}`);
      if (sr.why) paragraph(cleanReportText(sr.why));
    }) : paragraph('(none)');

    if (dream) {
      section('Narrative Synthesis');
      paragraph(`Quality: ${dream.dream_scores?.quality ?? '—'}/100 | Readiness: ${dream.dream_scores?.readiness ?? '—'}/100 | Commercial: ${dream.dream_scores?.commercial ?? '—'}/100 | Literary: ${dream.dream_scores?.literary ?? '—'}/100`);
      subhead('Executive Verdict');
      paragraph(cleanReportText(dream.executive_verdict));

      if (dream.market_shelf) {
        section('Market Shelf');
        labelValue('Best Shelf', cleanReportText(dream.market_shelf.best_shelf));
        labelValue('Marketable Hook', cleanReportText(dream.market_shelf.marketable_hook));
        labelValue('Market Danger', cleanReportText(dream.market_shelf.market_danger));
      }

      if (Array.isArray(dream.structural_stack) && dream.structural_stack.length > 0) {
        section('Structural Stack');
        dream.structural_stack.forEach((layer) => {
          subhead(`${cleanReportText(layer.layer_name)} — ${layer.status}`);
          paragraph(`Function: ${cleanReportText(layer.function)}`);
          paragraph(`Revision note: ${cleanReportText(layer.revision_note)}`);
        });
      }

      if (Array.isArray(dream.arc_map) && dream.arc_map.length > 0) {
        section('Arc Map');
        dream.arc_map.forEach((act) => {
          subhead(`${cleanReportText(act.act_name)} (${cleanReportText(act.chapter_range)})`);
          paragraph(`Function: ${cleanReportText(act.primary_function)}`);
          paragraph(`Revision priority: ${cleanReportText(act.revision_priority)}`);
        });
      }

      if (Array.isArray(dream.revision_plan) && dream.revision_plan.length > 0) {
        section('Revision Plan');
        dream.revision_plan.forEach((item) => {
          subhead(`Priority ${item.priority}: ${cleanReportText(item.title)}`);
          paragraph(`Goal: ${cleanReportText(item.goal)}`);
          if (Array.isArray(item.actions) && item.actions.length > 0) item.actions.forEach(bullet);
          if (item.acceptance_check) paragraph(`Acceptance check: ${cleanReportText(item.acceptance_check)}`);
        });
      }
    }

    section('Technical Metadata');
    labelValue('Job ID', jobId);
    labelValue('Schema', result.schema_version);
    paragraph(EXPORT_DISCLAIMER);

    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i += 1) {
      doc.switchToPage(i);
      const pageNumber = i - range.start + 1;
      doc.font('Helvetica').fontSize(7).fillColor(pageNumber === 1 ? BRAND.cream2 : BRAND.muted).text(
        pageNumber === 1 ? 'Powered by RevisionGrade™' : `RevisionGrade™ Evaluation Report · Confidential · Page ${pageNumber}`,
        doc.page.margins.left,
        doc.page.height - 42,
        { width: contentWidth, align: 'center' },
      );
      doc.fillColor('#000000');
    }

    doc.end();
  });
}

async function buildDocx(result: ExportableResult, title: string | null, jobId: string, dream: LongformDreamDocument | null): Promise<Buffer> {
  const metadata = buildMetadata(result, title, dream);
  const summaryFallback = buildSummaryFallback(result);
  const para = (text: string, opts: { bold?: boolean; size?: number; color?: string; align?: (typeof AlignmentType)[keyof typeof AlignmentType]; before?: number; after?: number } = {}) =>
    new Paragraph({
      alignment: opts.align,
      spacing: { before: opts.before ?? 80, after: opts.after ?? 220, line: 330 },
      children: [new TextRun({ text: cleanReportText(text), bold: opts.bold ?? false, size: opts.size ?? 22, color: opts.color ?? DOCX.text })],
    });
  const paras = (text: unknown, opts: { bold?: boolean; size?: number; color?: string; before?: number; after?: number } = {}) =>
    splitReportParagraphs(cleanReportText(text)).map((part) => para(part, opts));
  const heading = (text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel]) =>
    new Paragraph({
      heading: level,
      spacing: { before: level === HeadingLevel.HEADING_1 ? 320 : 460, after: 180 },
      children: [new TextRun({ text, bold: true, color: level === HeadingLevel.HEADING_1 ? DOCX.ink : DOCX.gold })],
    });
  const bulletPara = (text: string) => para(`• ${cleanReportText(text)}`, { after: 180 });
  const metaPara = (label: string, value: string | null) => value ? para(`${label}: ${value}`, { bold: true, color: DOCX.cream2, before: 40, after: 80 }) : null;

  const children: Paragraph[] = [];
  children.push(para('REVISIONGRADE™', { bold: true, size: 20, color: DOCX.gold, align: AlignmentType.CENTER, after: 80 }));
  children.push(heading('Evaluation Report', HeadingLevel.HEADING_1));
  children.push(para(metadata.displayTitle, { bold: true, size: 30, color: DOCX.ink, after: 280 }));
  [
    metaPara('Report Type', metadata.reportType),
    metaPara('Genre', metadata.genre),
    metaPara('Shelf', metadata.shelf),
    metaPara('Submitted Word Count', metadata.wordCount ? metadata.wordCount.toLocaleString() : null),
    metaPara('Estimated Manuscript Pages', metadata.estimatedPages ? `${metadata.estimatedPages.toLocaleString()} at ${WORDS_PER_MANUSCRIPT_PAGE} words/page` : null),
    metaPara('Generated', metadata.generatedAt),
    metaPara('Overall Score', metadata.score),
    metaPara('Verdict', metadata.verdict),
    metaPara('Confidentiality', 'Prepared for author/editorial use'),
  ].forEach((item) => { if (item) children.push(item); });
  children.push(para('Powered by RevisionGrade™. Author retains ownership of manuscript content.', { color: DOCX.cream2, size: 18, before: 260, after: 420 }));

  children.push(heading('Summary', HeadingLevel.HEADING_2));
  children.push(...paras(cleanReportText(result.overview.one_paragraph_summary, summaryFallback, { blockTruncation: true })));

  children.push(heading('Top Strengths', HeadingLevel.HEADING_2));
  result.overview.top_3_strengths.forEach((s) => children.push(bulletPara(s)));

  children.push(heading('Top Risks', HeadingLevel.HEADING_2));
  result.overview.top_3_risks.forEach((r) => children.push(bulletPara(r)));

  children.push(heading('Criteria Scores', HeadingLevel.HEADING_2));
  result.criteria.forEach((c) => {
    children.push(para(`${c.key} — ${scoreLabel(c.score_0_10, 10)}${c.confidence_level ? ` (${c.confidence_level} confidence)` : ''}`, { bold: true, color: DOCX.ink, before: 260, after: 100 }));
    if (c.rationale) children.push(...paras(c.rationale));
  });

  children.push(heading('Quick Wins', HeadingLevel.HEADING_2));
  if (result.recommendations.quick_wins.length === 0) children.push(para('(none)'));
  result.recommendations.quick_wins.forEach((qw) => {
    children.push(para(`• ${cleanReportText(qw.action)}  [effort: ${qw.effort}, impact: ${qw.impact}]`, { bold: true, color: DOCX.ink }));
    if (qw.why) children.push(...paras(qw.why));
  });

  children.push(heading('Strategic Revisions', HeadingLevel.HEADING_2));
  if (result.recommendations.strategic_revisions.length === 0) children.push(para('(none)'));
  result.recommendations.strategic_revisions.forEach((sr) => {
    children.push(para(`• ${cleanReportText(sr.action)}  [effort: ${sr.effort}, impact: ${sr.impact}]`, { bold: true, color: DOCX.ink }));
    if (sr.why) children.push(...paras(sr.why));
  });

  if (dream) {
    children.push(heading('Narrative Synthesis', HeadingLevel.HEADING_2));
    children.push(para(`Quality: ${dream.dream_scores?.quality ?? '—'}/100  |  Readiness: ${dream.dream_scores?.readiness ?? '—'}/100  |  Commercial: ${dream.dream_scores?.commercial ?? '—'}/100  |  Literary: ${dream.dream_scores?.literary ?? '—'}/100`, { bold: true, color: DOCX.gold }));
    children.push(heading('Executive Verdict', HeadingLevel.HEADING_3));
    children.push(...paras(dream.executive_verdict ?? '—'));

    if (dream.market_shelf) {
      children.push(heading('Market Shelf', HeadingLevel.HEADING_3));
      children.push(para(`Best Shelf: ${dream.market_shelf.best_shelf}`, { bold: true }));
      children.push(...paras(`Marketable Hook: ${dream.market_shelf.marketable_hook}`));
      if (Array.isArray(dream.market_shelf.shelf_neighbors)) dream.market_shelf.shelf_neighbors.forEach((item) => children.push(bulletPara(item)));
      children.push(...paras(`Market Danger: ${dream.market_shelf.market_danger}`));
    }

    if (Array.isArray(dream.structural_stack) && dream.structural_stack.length > 0) {
      children.push(heading('Structural Stack', HeadingLevel.HEADING_3));
      dream.structural_stack.forEach((layer) => {
        children.push(para(`${layer.layer_name} — ${layer.status}`, { bold: true, color: DOCX.ink }));
        children.push(...paras(`Function: ${layer.function}`));
        children.push(...paras(`Revision note: ${layer.revision_note}`));
      });
    }

    if (Array.isArray(dream.arc_map) && dream.arc_map.length > 0) {
      children.push(heading('Arc Map', HeadingLevel.HEADING_3));
      dream.arc_map.forEach((act) => {
        children.push(para(`${act.act_name} (${act.chapter_range})`, { bold: true, color: DOCX.ink }));
        children.push(...paras(`Function: ${act.primary_function}`));
        children.push(...paras(`Revision priority: ${act.revision_priority}`));
      });
    }

    if (Array.isArray(dream.revision_plan) && dream.revision_plan.length > 0) {
      children.push(heading('Revision Plan', HeadingLevel.HEADING_3));
      dream.revision_plan.forEach((item) => {
        children.push(para(`Priority ${item.priority}: ${item.title}`, { bold: true, color: DOCX.ink }));
        children.push(...paras(`Goal: ${item.goal}`));
        if (Array.isArray(item.actions)) item.actions.forEach((action) => children.push(bulletPara(action)));
        if (item.acceptance_check) children.push(...paras(`Acceptance check: ${item.acceptance_check}`));
      });
    }
  }

  children.push(heading('Technical Metadata', HeadingLevel.HEADING_2));
  children.push(para(`Job ID: ${jobId}`, { color: DOCX.cream2 }));
  children.push(para(`Schema: ${result.schema_version}`, { color: DOCX.cream2 }));
  children.push(para(EXPORT_DISCLAIMER, { color: DOCX.cream2, size: 18, before: 260 }));

  const doc = new Document({ sections: [{ children }] });
  return await Packer.toBuffer(doc);
}

async function loadCanonicalEvaluationResult(admin: ReturnType<typeof createAdminClient>, jobId: string): Promise<unknown | null> {
  const { data: artifact } = await admin
    .from('evaluation_artifacts')
    .select('content')
    .eq('job_id', jobId)
    .in('artifact_type', ['evaluation_result_v2', 'evaluation_result_v1'])
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  return artifact?.content ?? null;
}

async function loadDreamDocument(admin: ReturnType<typeof createAdminClient>, jobId: string): Promise<LongformDreamDocument | null> {
  const { data: dreamRow } = await admin
    .from('evaluation_artifacts')
    .select('content')
    .eq('job_id', jobId)
    .eq('artifact_type', 'longform_document_v1')
    .maybeSingle();
  const content = dreamRow?.content as { longform_document?: unknown } | null | undefined;
  if (content?.longform_document && typeof content.longform_document === 'object') {
    return content.longform_document as LongformDreamDocument;
  }
  return null;
}

export async function GET(
  request: NextRequest,
  { params }: { params: { jobId: string } | Promise<{ jobId: string }> },
) {
  const resolved = await Promise.resolve(params);
  const jobId = resolved.jobId;

  if (!jobId || !UUID_RE.test(jobId)) {
    return NextResponse.json({ error: 'Invalid job ID' }, { status: 400 });
  }

  const { searchParams } = new URL(request.url);
  const formatParam = (searchParams.get('format') ?? 'txt').toLowerCase();
  if (!['pdf', 'docx', 'txt'].includes(formatParam)) {
    return NextResponse.json({ error: 'Invalid format' }, { status: 400 });
  }
  const format = formatParam as ExportFormat;

  const ssrSupabase = await createSSRClient();
  const {
    data: { user },
  } = await ssrSupabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const admin = createAdminClient();
  const { data: job, error } = await admin
    .from('evaluation_jobs')
    .select(`evaluation_result, status, validity_status, manuscripts!inner(user_id, title)`)
    .eq('id', jobId)
    .eq('manuscripts.user_id', user.id)
    .single();

  if (error || !job) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  const canonicalResult = await loadCanonicalEvaluationResult(admin, jobId);
  const rawResult = canonicalResult ?? (job.evaluation_result as unknown);

  if (!rawResult || !canReleaseEvaluationRead({ ...job, evaluation_result: rawResult })) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  if (!isExportableResultCandidate(rawResult)) {
    return NextResponse.json({ error: 'Invalid result format' }, { status: 500 });
  }

  const result = rawResult as ExportableResult;
  const relationTitle = extractManuscriptTitle((job as { manuscripts?: unknown }).manuscripts);
  const title = relationTitle ?? result.metrics?.manuscript?.title ?? null;
  const dream = await loadDreamDocument(admin, jobId);

  if (format === 'txt') {
    const body = buildTxtReport(result, title, jobId, dream);
    return new Response(body, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'txt')}"`,
        'Cache-Control': 'no-store',
      },
    });
  }

  if (format === 'pdf') {
    const buffer = await buildPdfReport(result, title, jobId, dream);
    return new Response(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'pdf')}"`,
        'Cache-Control': 'no-store',
      },
    });
  }

  const buffer = await buildDocx(result, title, jobId, dream);
  return new Response(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'docx')}"`,
      'Cache-Control': 'no-store',
    },
  });
}
