import 'server-only';
import { NextRequest, NextResponse } from 'next/server';
import PDFDocument from 'pdfkit';
import { createClient as createSSRClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { canReleaseEvaluationRead } from '@/lib/jobs/readReleaseGate';
import { isEvaluationResultV1, type EvaluationResultV1 } from '@/schemas/evaluation-result-v1';
import type { LongformDreamDocument } from '@/lib/evaluation/pipeline/runPass3bLongform';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Footer,
} from 'docx';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const TRADEMARK_LIST = 'RevisionGrade™, Agent Readiness™, Storygate Studio™, Golden Spine™, and TrustPath™ are trademarks of RevisionGrade.';

type ExportFormat = 'pdf' | 'docx' | 'txt';

type ArtifactBranding = {
  title: string;
  manuscriptTitle: string;
  jobId: string;
  generatedAt: string;
  tierLabel: string;
  footerLine: string;
  ownershipLine: string;
  artifactNoticeLines: string[];
};

function safeFilename(title: string | null, jobId: string, ext: string): string {
  const base = title ? title.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 40) : jobId.slice(0, 8);
  return `revision-grade-${base}.${ext}`;
}

function extractManuscriptTitle(manuscripts: unknown): string | null {
  const relation = Array.isArray(manuscripts) ? manuscripts[0] : manuscripts;
  const title =
    typeof relation === 'object' && relation && 'title' in relation
      ? (relation as { title?: unknown }).title
      : null;
  return typeof title === 'string' && title.trim().length > 0 ? title.trim() : null;
}

function resolveTierLabel(result: EvaluationResultV1, dream: LongformDreamDocument | null): string {
  const wordCount = result.metrics?.manuscript?.word_count;
  if (dream || (typeof wordCount === 'number' && wordCount >= 25000)) return 'Long-Form Evaluation';
  return 'Evaluation Report';
}

function buildArtifactBranding(args: {
  result: EvaluationResultV1;
  title: string | null;
  jobId: string;
  dream: LongformDreamDocument | null;
}): ArtifactBranding {
  const generatedAt = args.result.generated_at || new Date().toISOString();
  const manuscriptTitle = args.title ?? args.result.metrics?.manuscript?.title ?? 'Untitled';
  const tierLabel = resolveTierLabel(args.result, args.dream);
  const footerLine = `Generated by RevisionGrade™ · © ${new Date(generatedAt).getFullYear()} RevisionGrade. All rights reserved. · Job ID: ${args.jobId} · ${generatedAt}`;
  const ownershipLine = 'Author owns manuscript content. RevisionGrade owns the diagnostic framework, scoring methodology, report structure, templates, taxonomy, and evaluation format.';

  return {
    title: 'RevisionGrade™ Evaluation Report',
    manuscriptTitle,
    jobId: args.jobId,
    generatedAt,
    tierLabel,
    footerLine,
    ownershipLine,
    artifactNoticeLines: [
      'Artifact Notice',
      '',
      'This Evaluation Report was generated by RevisionGrade™.',
      'The submitting author retains ownership of the manuscript, story materials, characters, and underlying creative work.',
      'RevisionGrade retains ownership of its diagnostic framework, scoring methodology, evaluation taxonomy, report structure, templates, user interface language, artifact formatting system, and platform-generated analysis format.',
      '',
      'This report is licensed for use by the submitting author only. It may not be reproduced, resold, redistributed, repackaged, modified, or offered as a standalone product or competing editorial service.',
      '',
      'This report is an AI-assisted diagnostic assessment. It does not constitute professional editorial, literary agency, legal, financial, or publishing advice. Publishing outcomes depend on market conditions, agent fit, reader preference, editorial judgment, and other factors outside RevisionGrade’s control.',
      '',
      TRADEMARK_LIST,
      'For support or licensing inquiries, contact RevisionGrade through revisiongrade.com/contact.',
    ],
  };
}

function appendDreamTxtSections(lines: string[], dream: LongformDreamDocument): void {
  const sep = '='.repeat(72);
  const push = (s: string) => lines.push(s);

  push('');
  push(sep);
  push('NARRATIVE SYNTHESIS — HOLISTIC CRAFT ASSESSMENT');
  push(sep);
  push('');
  push(`Quality: ${dream.dream_scores?.quality ?? '—'}/100`);
  push(`Readiness: ${dream.dream_scores?.readiness ?? '—'}/100`);
  push(`Commercial: ${dream.dream_scores?.commercial ?? '—'}/100`);
  push(`Literary: ${dream.dream_scores?.literary ?? '—'}/100`);
  push('');
  push('Executive Verdict:');
  push(dream.executive_verdict ?? '—');
  push('');

  if (dream.market_shelf) {
    push('Market Shelf:');
    push(`  Best shelf: ${dream.market_shelf.best_shelf ?? '—'}`);
    push(`  Marketable hook: ${dream.market_shelf.marketable_hook ?? '—'}`);
    push(`  Market danger: ${dream.market_shelf.market_danger ?? '—'}`);
    push('');
  }

  if (Array.isArray(dream.criterion_analyses) && dream.criterion_analyses.length > 0) {
    push(sep);
    push('DREAM ANALYSIS — PER-CRITERION');
    push(sep);
    dream.criterion_analyses.forEach((a) => {
      push('');
      push(`${a.key} — ${a.score}/10 (${a.confidence} confidence)`);
      if (Array.isArray(a.fit_evidence) && a.fit_evidence.length > 0) push(`  Fit evidence: ${a.fit_evidence.join('; ')}`);
      if (Array.isArray(a.gap_evidence) && a.gap_evidence.length > 0) push(`  Gap evidence: ${a.gap_evidence.join('; ')}`);
      if (Array.isArray(a.revision_queue) && a.revision_queue.length > 0) push(`  Revision queue: ${a.revision_queue.join('; ')}`);
    });
  }

  if (Array.isArray(dream.revision_plan) && dream.revision_plan.length > 0) {
    push('');
    push(sep);
    push('REVISION PLAN');
    push(sep);
    dream.revision_plan.forEach((item) => {
      push('');
      push(`Priority ${item.priority}: ${item.title}`);
      push(`  Goal: ${item.goal}`);
      if (Array.isArray(item.actions) && item.actions.length > 0) push(`  Actions: ${item.actions.join('; ')}`);
      if (item.acceptance_check) push(`  Acceptance check: ${item.acceptance_check}`);
    });
  }
}

function buildTxtReport(
  result: EvaluationResultV1,
  dream: LongformDreamDocument | null,
  branding: ArtifactBranding,
): string {
  const lines: string[] = [];
  const sep = '='.repeat(72);
  const sub = '-'.repeat(72);

  lines.push(sep);
  lines.push(branding.title.toUpperCase());
  lines.push(branding.manuscriptTitle);
  lines.push(sep);
  lines.push(`Job ID: ${branding.jobId}`);
  lines.push(`Generated: ${branding.generatedAt}`);
  lines.push(`Tier: ${branding.tierLabel}`);
  lines.push('');
  lines.push(`Verdict: ${result.overview.verdict.toUpperCase()}`);
  lines.push(`Overall Score: ${result.overview.overall_score_0_100}/100`);
  lines.push('');

  lines.push(sub);
  lines.push('SUMMARY');
  lines.push(sub);
  lines.push(result.overview.one_paragraph_summary);
  lines.push('');

  lines.push(sub);
  lines.push('TOP STRENGTHS');
  lines.push(sub);
  result.overview.top_3_strengths.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
  lines.push('');

  lines.push(sub);
  lines.push('TOP RISKS');
  lines.push(sub);
  result.overview.top_3_risks.forEach((r, i) => lines.push(`${i + 1}. ${r}`));
  lines.push('');

  lines.push(sub);
  lines.push('CRITERIA SCORES');
  lines.push(sub);
  result.criteria.forEach((c) => {
    lines.push(`• ${c.key} — ${c.score_0_10}/10${c.confidence_level ? ` (${c.confidence_level} confidence)` : ''}`);
    if (c.rationale) lines.push(`  Rationale: ${c.rationale}`);
    lines.push('');
  });

  lines.push(sub);
  lines.push('QUICK WINS');
  lines.push(sub);
  if (result.recommendations.quick_wins.length === 0) lines.push('(none)');
  result.recommendations.quick_wins.forEach((qw, i) => {
    lines.push(`${i + 1}. ${qw.action} [effort: ${qw.effort}, impact: ${qw.impact}]`);
    if (qw.why) lines.push(`   Why: ${qw.why}`);
  });
  lines.push('');

  lines.push(sub);
  lines.push('STRATEGIC REVISIONS');
  lines.push(sub);
  if (result.recommendations.strategic_revisions.length === 0) lines.push('(none)');
  result.recommendations.strategic_revisions.forEach((sr, i) => {
    lines.push(`${i + 1}. ${sr.action} [effort: ${sr.effort}, impact: ${sr.impact}]`);
    if (sr.why) lines.push(`   Why: ${sr.why}`);
  });

  if (dream) appendDreamTxtSections(lines, dream);

  lines.push('');
  lines.push(sep);
  lines.push(...branding.artifactNoticeLines);
  lines.push(sep);
  lines.push(branding.footerLine);
  lines.push(branding.ownershipLine);

  return lines.join('\n');
}

async function buildPdfReport(
  result: EvaluationResultV1,
  dream: LongformDreamDocument | null,
  branding: ArtifactBranding,
): Promise<Buffer> {
  return await new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margin: 54,
      bufferPages: true,
      info: {
        Title: `${branding.title} - ${branding.manuscriptTitle}`,
        Author: 'RevisionGrade',
        Subject: branding.tierLabel,
        Creator: 'RevisionGrade Export Engine',
        Producer: 'RevisionGrade Export Engine',
        Keywords: 'RevisionGrade, manuscript evaluation, diagnostic report',
      },
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer | Uint8Array) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const contentWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const bottomY = () => doc.page.height - doc.page.margins.bottom - 42;
    const ensureSpace = (height = 90) => {
      if (doc.y + height > bottomY()) doc.addPage();
    };
    const section = (text: string) => {
      ensureSpace(70);
      doc.moveDown(0.8);
      doc.font('Helvetica-Bold').fontSize(15).text(text, { width: contentWidth });
      doc.moveDown(0.35);
      doc.moveTo(doc.page.margins.left, doc.y).lineTo(doc.page.margins.left + contentWidth, doc.y).strokeColor('#CCCCCC').stroke();
      doc.strokeColor('#000000');
      doc.moveDown(0.5);
    };
    const paragraph = (text: string) => {
      ensureSpace(70);
      doc.font('Helvetica').fontSize(10.5).text(text || '—', { width: contentWidth });
      doc.moveDown(0.45);
    };
    const bullet = (text: string) => {
      ensureSpace(45);
      doc.font('Helvetica').fontSize(10.5).text(`• ${text}`, { width: contentWidth, indent: 12 });
      doc.moveDown(0.25);
    };

    doc.font('Helvetica-Bold').fontSize(24).text(branding.title, { width: contentWidth });
    doc.moveDown(0.25);
    doc.font('Helvetica-Bold').fontSize(14).text(branding.manuscriptTitle, { width: contentWidth });
    doc.moveDown(0.25);
    doc.font('Helvetica').fontSize(10).text(`Job ID: ${branding.jobId}`, { width: contentWidth });
    doc.text(`Generated: ${branding.generatedAt}`, { width: contentWidth });
    doc.text(`Tier: ${branding.tierLabel}`, { width: contentWidth });
    doc.moveDown(0.45);
    doc.font('Helvetica-Bold').fontSize(12).text(
      `Verdict: ${result.overview.verdict.toUpperCase()}   |   Score: ${result.overview.overall_score_0_100}/100`,
      { width: contentWidth },
    );

    section('Summary');
    paragraph(result.overview.one_paragraph_summary);

    section('Top Strengths');
    result.overview.top_3_strengths.length ? result.overview.top_3_strengths.forEach(bullet) : paragraph('(none)');

    section('Top Risks');
    result.overview.top_3_risks.length ? result.overview.top_3_risks.forEach(bullet) : paragraph('(none)');

    section('Criteria Scores');
    result.criteria.forEach((c) => {
      ensureSpace(90);
      doc.font('Helvetica-Bold').fontSize(11).text(
        `${c.key} — ${c.score_0_10}/10${c.confidence_level ? ` (${c.confidence_level} confidence)` : ''}`,
        { width: contentWidth },
      );
      if (c.rationale) paragraph(c.rationale);
    });

    section('Quick Wins');
    result.recommendations.quick_wins.length ? result.recommendations.quick_wins.forEach((qw, idx) => {
      ensureSpace(80);
      doc.font('Helvetica-Bold').fontSize(10.5).text(`${idx + 1}. ${qw.action}  [effort: ${qw.effort}, impact: ${qw.impact}]`, { width: contentWidth });
      if (qw.why) paragraph(qw.why);
    }) : paragraph('(none)');

    section('Strategic Revisions');
    result.recommendations.strategic_revisions.length ? result.recommendations.strategic_revisions.forEach((sr, idx) => {
      ensureSpace(80);
      doc.font('Helvetica-Bold').fontSize(10.5).text(`${idx + 1}. ${sr.action}  [effort: ${sr.effort}, impact: ${sr.impact}]`, { width: contentWidth });
      if (sr.why) paragraph(sr.why);
    }) : paragraph('(none)');

    if (dream) {
      section('Narrative Synthesis');
      paragraph(`Quality: ${dream.dream_scores?.quality ?? '—'}/100 | Readiness: ${dream.dream_scores?.readiness ?? '—'}/100 | Commercial: ${dream.dream_scores?.commercial ?? '—'}/100 | Literary: ${dream.dream_scores?.literary ?? '—'}/100`);
      doc.font('Helvetica-Bold').fontSize(12).text('Executive Verdict', { width: contentWidth });
      paragraph(dream.executive_verdict ?? '—');

      if (Array.isArray(dream.criterion_analyses) && dream.criterion_analyses.length > 0) {
        section('DREAM Analysis');
        dream.criterion_analyses.forEach((a) => {
          ensureSpace(90);
          doc.font('Helvetica-Bold').fontSize(11).text(`${a.key} — ${a.score}/10 (${a.confidence} confidence)`, { width: contentWidth });
          if (Array.isArray(a.fit_evidence) && a.fit_evidence.length > 0) paragraph(`Fit evidence: ${a.fit_evidence.join('; ')}`);
          if (Array.isArray(a.gap_evidence) && a.gap_evidence.length > 0) paragraph(`Gap evidence: ${a.gap_evidence.join('; ')}`);
          if (Array.isArray(a.revision_queue) && a.revision_queue.length > 0) paragraph(`Revision queue: ${a.revision_queue.join('; ')}`);
        });
      }

      if (Array.isArray(dream.revision_plan) && dream.revision_plan.length > 0) {
        section('Revision Plan');
        dream.revision_plan.forEach((item) => {
          ensureSpace(90);
          doc.font('Helvetica-Bold').fontSize(11).text(`Priority ${item.priority}: ${item.title}`, { width: contentWidth });
          paragraph(`Goal: ${item.goal}`);
          if (Array.isArray(item.actions) && item.actions.length > 0) paragraph(`Actions: ${item.actions.join('; ')}`);
          if (item.acceptance_check) paragraph(`Acceptance check: ${item.acceptance_check}`);
        });
      }
    }

    doc.addPage();
    section('Artifact Notice');
    branding.artifactNoticeLines.slice(2).forEach(paragraph);

    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i += 1) {
      doc.switchToPage(i);
      const footerY = doc.page.height - 42;
      doc.font('Helvetica').fontSize(7).fillColor('#4B5563').text(branding.footerLine, doc.page.margins.left, footerY, { width: contentWidth, align: 'center' });
      doc.font('Helvetica').fontSize(6.5).fillColor('#4B5563').text(branding.ownershipLine, doc.page.margins.left, footerY + 10, { width: contentWidth, align: 'center' });
      doc.fillColor('#000000');
    }

    doc.end();
  });
}

async function buildDocx(
  result: EvaluationResultV1,
  dream: LongformDreamDocument | null,
  branding: ArtifactBranding,
): Promise<Buffer> {
  const para = (text: string, opts: { bold?: boolean; size?: number } = {}) =>
    new Paragraph({ children: [new TextRun({ text, bold: opts.bold ?? false, size: opts.size })] });
  const heading = (text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel]) =>
    new Paragraph({ heading: level, children: [new TextRun({ text })] });

  const children: Paragraph[] = [];
  children.push(heading(branding.title, HeadingLevel.HEADING_1));
  children.push(para(branding.manuscriptTitle, { bold: true, size: 28 }));
  children.push(para(`Job ID: ${branding.jobId}`));
  children.push(para(`Generated: ${branding.generatedAt}`));
  children.push(para(`Tier: ${branding.tierLabel}`));
  children.push(para(`Verdict: ${result.overview.verdict.toUpperCase()}  |  Score: ${result.overview.overall_score_0_100}/100`, { bold: true }));
  children.push(para(''));

  children.push(heading('Summary', HeadingLevel.HEADING_2));
  children.push(para(result.overview.one_paragraph_summary));

  children.push(heading('Top Strengths', HeadingLevel.HEADING_2));
  result.overview.top_3_strengths.forEach((s) => children.push(para(`• ${s}`)));

  children.push(heading('Top Risks', HeadingLevel.HEADING_2));
  result.overview.top_3_risks.forEach((r) => children.push(para(`• ${r}`)));

  children.push(heading('Criteria Scores', HeadingLevel.HEADING_2));
  result.criteria.forEach((c) => {
    children.push(para(`${c.key} — ${c.score_0_10}/10${c.confidence_level ? ` (${c.confidence_level} confidence)` : ''}`, { bold: true }));
    if (c.rationale) children.push(para(c.rationale));
  });

  children.push(heading('Quick Wins', HeadingLevel.HEADING_2));
  if (result.recommendations.quick_wins.length === 0) children.push(para('(none)'));
  result.recommendations.quick_wins.forEach((qw) => {
    children.push(para(`• ${qw.action}  [effort: ${qw.effort}, impact: ${qw.impact}]`, { bold: true }));
    if (qw.why) children.push(para(`   ${qw.why}`));
  });

  children.push(heading('Strategic Revisions', HeadingLevel.HEADING_2));
  if (result.recommendations.strategic_revisions.length === 0) children.push(para('(none)'));
  result.recommendations.strategic_revisions.forEach((sr) => {
    children.push(para(`• ${sr.action}  [effort: ${sr.effort}, impact: ${sr.impact}]`, { bold: true }));
    if (sr.why) children.push(para(`   ${sr.why}`));
  });

  if (dream) {
    children.push(heading('Narrative Synthesis', HeadingLevel.HEADING_2));
    children.push(para(`Quality: ${dream.dream_scores?.quality ?? '—'}/100  |  Readiness: ${dream.dream_scores?.readiness ?? '—'}/100  |  Commercial: ${dream.dream_scores?.commercial ?? '—'}/100  |  Literary: ${dream.dream_scores?.literary ?? '—'}/100`, { bold: true }));
    children.push(heading('Executive Verdict', HeadingLevel.HEADING_3));
    children.push(para(dream.executive_verdict ?? '—'));

    if (Array.isArray(dream.criterion_analyses) && dream.criterion_analyses.length > 0) {
      children.push(heading('DREAM Analysis', HeadingLevel.HEADING_2));
      dream.criterion_analyses.forEach((a) => {
        children.push(para(`${a.key} — ${a.score}/10 (${a.confidence} confidence)`, { bold: true }));
        if (Array.isArray(a.fit_evidence) && a.fit_evidence.length > 0) children.push(para(`Fit evidence: ${a.fit_evidence.join('; ')}`));
        if (Array.isArray(a.gap_evidence) && a.gap_evidence.length > 0) children.push(para(`Gap evidence: ${a.gap_evidence.join('; ')}`));
        if (Array.isArray(a.revision_queue) && a.revision_queue.length > 0) children.push(para(`Revision queue: ${a.revision_queue.join('; ')}`));
      });
    }
  }

  children.push(heading('Artifact Notice', HeadingLevel.HEADING_2));
  branding.artifactNoticeLines.slice(2).forEach((line) => children.push(para(line)));

  const doc = new Document({
    sections: [
      {
        footers: {
          default: new Footer({
            children: [
              para(branding.footerLine, { size: 14 }),
              para(branding.ownershipLine, { size: 14 }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}

export async function GET(
  request: NextRequest,
  { params }: { params: { jobId: string } | Promise<{ jobId: string }> },
) {
  const resolved = await Promise.resolve(params);
  const jobId = resolved.jobId;

  if (!jobId || !UUID_RE.test(jobId)) {
    return NextResponse.json({ error: 'Invalid job ID' }, { status: 400 });
  }

  const { searchParams } = new URL(request.url);
  const formatParam = (searchParams.get('format') ?? 'txt').toLowerCase();
  if (!['pdf', 'docx', 'txt'].includes(formatParam)) {
    return NextResponse.json({ error: 'Invalid format' }, { status: 400 });
  }
  const format = formatParam as ExportFormat;

  const ssrSupabase = await createSSRClient();
  const {
    data: { user },
  } = await ssrSupabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const admin = createAdminClient();
  const { data: job, error } = await admin
    .from('evaluation_jobs')
    .select(`evaluation_result, status, validity_status, manuscripts!inner(user_id, title)`)
    .eq('id', jobId)
    .eq('manuscripts.user_id', user.id)
    .single();

  if (error || !job || !canReleaseEvaluationRead(job) || !job.evaluation_result) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  if (!isEvaluationResultV1(job.evaluation_result as unknown)) {
    return NextResponse.json({ error: 'Invalid result format' }, { status: 500 });
  }

  const result = job.evaluation_result as EvaluationResultV1;
  const title = extractManuscriptTitle((job as { manuscripts?: unknown }).manuscripts);

  let dream: LongformDreamDocument | null = null;
  const { data: dreamRow } = await admin
    .from('evaluation_artifacts')
    .select('content')
    .eq('job_id', jobId)
    .eq('artifact_type', 'longform_document_v1')
    .maybeSingle();
  const content = dreamRow?.content as { longform_document?: unknown } | null | undefined;
  if (content?.longform_document && typeof content.longform_document === 'object') {
    dream = content.longform_document as LongformDreamDocument;
  }

  const branding = buildArtifactBranding({ result, title, jobId, dream });

  if (format === 'txt') {
    const body = buildTxtReport(result, dream, branding);
    return new Response(body, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'txt')}"`,
        'Cache-Control': 'no-store',
      },
    });
  }

  if (format === 'pdf') {
    const buffer = await buildPdfReport(result, dream, branding);
    return new Response(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'pdf')}"`,
        'Cache-Control': 'no-store',
      },
    });
  }

  const buffer = await buildDocx(result, dream, branding);
  return new Response(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'docx')}"`,
      'Cache-Control': 'no-store',
    },
  });
}
