import 'server-only';
import { NextRequest, NextResponse } from 'next/server';
import PDFDocument from 'pdfkit';
import { createClient as createSSRClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { canReleaseEvaluationRead } from '@/lib/jobs/readReleaseGate';
import { isEvaluationResultV1, type EvaluationResultV1 } from '@/schemas/evaluation-result-v1';
import { isEvaluationResultV2, type EvaluationResultV2 } from '@/schemas/evaluation-result-v2';
import type { LongformDreamDocument } from '@/lib/evaluation/pipeline/runPass3bLongform';
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  Table, TableRow, TableCell, WidthType, BorderStyle,
  AlignmentType, ShadingType, Header, Footer,
  PageNumber,
} from 'docx';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const LONG_FORM_WORD_THRESHOLD = 25000;
const WORDS_PER_MANUSCRIPT_PAGE = 250;
const EXPORT_DISCLAIMER =
  'Generated by RevisionGrade™. Author retains ownership of manuscript content. This report is an editorial diagnostic and does not guarantee publication, representation, or commercial outcome.';

// ── RevisionGrade brand palette ──────────────────────────────────────
const RG = {
  gold:       '#B8922A',
  goldLight:  '#F5E9C8',
  goldMid:    '#C8A96E',
  oxblood:    '#8B2E2E',
  ink:        '#1C1814',
  ink2:       '#2A2520',
  cream:      '#F5EFE0',
  cream2:     '#C8BEA8',
  surface:    '#FAF7F2',
  surfaceAlt: '#FFFDF9',
  border:     '#D9D0C3',
  textPrimary:'#1C1814',
  textMuted:  '#5C5549',
  textFaint:  '#9A9087',
  success:    '#3A6B2A',
  successBg:  '#EBF4E6',
  warning:    '#8B5E1A',
  warningBg:  '#FBF1DC',
  error:      '#8B2020',
  errorBg:    '#F9E8E8',
} as const;

const FOOTER_LINE = 'RevisionGrade(TM)  |  Manuscript diagnosis, author-controlled revision, and professional submission preparation.';

type ExportFormat = 'pdf' | 'docx' | 'txt';
type ExportableResult = EvaluationResultV1 | EvaluationResultV2;

type ExportableResultShape = {
  generated_at?: unknown;
  schema_version?: unknown;
  metrics?: { manuscript?: { title?: unknown; word_count?: unknown; genre?: unknown } };
  overview?: {
    verdict?: unknown;
    overall_score_0_100?: unknown;
    one_paragraph_summary?: unknown;
    top_3_strengths?: unknown;
    top_3_risks?: unknown;
  };
  criteria?: unknown;
  recommendations?: {
    quick_wins?: unknown;
    strategic_revisions?: unknown;
  };
};

type ReportMetadata = {
  displayTitle: string;
  generatedAt: string;
  score: string;
  verdict: string;
  wordCount: number | null;
  estimatedPages: number | null;
  reportType: string;
  shelf: string | null;
  genre: string | null;
};

function isExportableResultCandidate(value: unknown): value is ExportableResult {
  if (isEvaluationResultV1(value) || isEvaluationResultV2(value)) return true;

  if (!value || typeof value !== 'object') return false;

  const candidate = value as ExportableResultShape;
  return (
    typeof candidate.generated_at === 'string' &&
    typeof candidate.overview?.verdict === 'string' &&
    typeof candidate.overview?.one_paragraph_summary === 'string' &&
    Array.isArray(candidate.overview?.top_3_strengths) &&
    Array.isArray(candidate.overview?.top_3_risks) &&
    Array.isArray(candidate.criteria) &&
    Array.isArray(candidate.recommendations?.quick_wins) &&
    Array.isArray(candidate.recommendations?.strategic_revisions)
  );
}

function safeFilename(title: string | null, jobId: string, ext: string): string {
  const base = title ? title.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 40) : jobId.slice(0, 8);
  return `revision-grade-${base}.${ext}`;
}

function extractManuscriptTitle(manuscripts: unknown): string | null {
  const relation = Array.isArray(manuscripts) ? manuscripts[0] : manuscripts;
  const title =
    typeof relation === 'object' && relation && 'title' in relation
      ? (relation as { title?: unknown }).title
      : null;
  return typeof title === 'string' && title.trim().length > 0 ? title.trim() : null;
}

function asText(value: unknown): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null;
}

function scoreLabel(score: number | null | undefined, denominator: number): string {
  return typeof score === 'number' ? `${Math.round(score)}/${denominator}` : `—/${denominator}`;
}

function estimatePages(wordCount: number | null): number | null {
  if (typeof wordCount !== 'number' || !Number.isFinite(wordCount) || wordCount <= 0) return null;
  return Math.max(1, Math.ceil(wordCount / WORDS_PER_MANUSCRIPT_PAGE));
}

function inferReportType(wordCount: number | null): string {
  if (typeof wordCount !== 'number' || !Number.isFinite(wordCount)) return 'Evaluation Report';
  return wordCount >= LONG_FORM_WORD_THRESHOLD ? 'Long-form Evaluation Report' : 'Short-form Evaluation Report';
}

function stripMachineResidue(text: string): string {
  return text
    .replace(/\bindirect_speech\b/g, 'indirect speech')
    .replace(/\breported_speech\b/g, 'reported speech')
    .replace(/\btagged_speech\b/g, 'tagged speech')
    .replace(/\baction_beat_attribution\b/g, 'action-beat attribution')
    .replace(/\s+/g, ' ')
    .trim();
}

function looksTruncated(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) return true;
  if (/\blean on extend\.?$/i.test(trimmed)) return true;
  if (/\b(?:and|or|but|while|because|although|through|with|to|from|into|across|between|including|against)$/i.test(trimmed)) return true;
  return trimmed.length > 120 && !/[.!?”’)]$/.test(trimmed);
}

function buildSummaryFallback(result: ExportableResult): string {
  const strengths = result.overview.top_3_strengths.map(stripMachineResidue).filter(Boolean);
  const risks = result.overview.top_3_risks.map(stripMachineResidue).filter(Boolean);
  const strengthSentence = strengths.length
    ? `The strongest areas are: ${strengths.slice(0, 2).join('; ')}.`
    : 'The strongest areas are detailed in the criteria analysis.';
  const riskSentence = risks.length
    ? `The primary risks are: ${risks.slice(0, 2).join('; ')}.`
    : 'The primary risks are detailed in the criteria analysis.';
  return `${strengthSentence} ${riskSentence}`;
}

function safeTruncateText(text: string): string {
  const trimmed = text.trim();
  if (!trimmed) return trimmed;
  if (/[.!?;:—"')\]]\s*$/.test(trimmed)) return trimmed;
  const lastSpace = trimmed.lastIndexOf(' ');
  if (lastSpace === -1) return trimmed;
  const lastSegment = trimmed.slice(lastSpace + 1);
  if (lastSegment.length <= 3 && !/[aeiou]/i.test(lastSegment)) {
    const upToLastSpace = trimmed.slice(0, lastSpace).trimEnd();
    const cleaned = upToLastSpace.replace(/\s+(and|or|but|the|a|an|in|on|at|to|of|for|with|by)\s*$/i, '');
    return cleaned.replace(/[,;:\s]+$/, '') + '...';
  }
  return trimmed;
}

function cleanReportText(text: unknown, fallback = '—', options: { blockTruncation?: boolean } = {}): string {
  const raw = asText(text);
  if (!raw) return fallback;
  const cleaned = stripMachineResidue(raw);
  if (options.blockTruncation && looksTruncated(cleaned)) {
    return safeTruncateText(cleaned) || fallback;
  }
  return cleaned;
}

function toPdfSafeText(value: unknown, fallback = '-'): string {
  return cleanReportText(value, fallback)
    .normalize('NFKC')
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, '')
    .replace(/[\u2018\u2019\u201A\u201B]/g, "'")
    .replace(/[\u201C\u201D\u201E\u201F]/g, '"')
    .replace(/[\u2013\u2014\u2212]/g, '-')
    .replace(/\u2022/g, '-')
    .replace(/\u2122/g, '(TM)')
    .replace(/\u00AE/g, '(R)')
    .replace(/\u00A9/g, '(C)')
    .replace(/\u00A0/g, ' ')
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, '?')
    .trim();
}

function buildMetadata(result: ExportableResult, title: string | null, dream: LongformDreamDocument | null): ReportMetadata {
  const wordCount = typeof result.metrics?.manuscript?.word_count === 'number' ? result.metrics.manuscript.word_count : null;
  const displayTitle = title ?? result.metrics?.manuscript?.title ?? 'Untitled Manuscript';
  const shelf = dream?.market_shelf?.best_shelf ?? null;
  const genre = result.metrics?.manuscript?.genre ?? null;
  return {
    displayTitle,
    generatedAt: result.generated_at,
    score: scoreLabel(result.overview.overall_score_0_100, 100),
    verdict: result.overview.verdict.toUpperCase(),
    wordCount,
    estimatedPages: estimatePages(wordCount),
    reportType: inferReportType(wordCount),
    shelf,
    genre: genre ?? null,
  };
}

function appendDreamTxtSections(lines: string[], dream: LongformDreamDocument): void {
  const sep = '='.repeat(72);
  const sub = '-'.repeat(72);
  const push = (s: string) => lines.push(s);

  push('');
  push(sep);
  push('NARRATIVE SYNTHESIS — HOLISTIC CRAFT ASSESSMENT');
  push(sep);
  push('');
  push(`Quality: ${dream.dream_scores?.quality ?? '—'}/100`);
  push(`Readiness: ${dream.dream_scores?.readiness ?? '—'}/100`);
  push(`Commercial: ${dream.dream_scores?.commercial ?? '—'}/100`);
  push(`Literary: ${dream.dream_scores?.literary ?? '—'}/100`);
  push('');
  push('Executive Verdict:');
  push(cleanReportText(dream.executive_verdict));

  if (dream.market_shelf) {
    push('');
    push(sub);
    push('MARKET SHELF');
    push(sub);
    push(`Best shelf: ${cleanReportText(dream.market_shelf.best_shelf)}`);
    push(`Marketable hook: ${cleanReportText(dream.market_shelf.marketable_hook)}`);
    if (Array.isArray(dream.market_shelf.shelf_neighbors) && dream.market_shelf.shelf_neighbors.length > 0) {
      push('Shelf neighbors:');
      dream.market_shelf.shelf_neighbors.forEach((item) => push(`  • ${cleanReportText(item)}`));
    }
    if (Array.isArray(dream.market_shelf.comparison_space) && dream.market_shelf.comparison_space.length > 0) {
      push('Comparison space:');
      dream.market_shelf.comparison_space.forEach((item) => push(`  • ${cleanReportText(item)}`));
    }
    push(`Market danger: ${cleanReportText(dream.market_shelf.market_danger)}`);
  }

  if (Array.isArray(dream.structural_stack) && dream.structural_stack.length > 0) {
    push('');
    push(sub);
    push('STRUCTURAL STACK');
    push(sub);
    dream.structural_stack.forEach((layer) => {
      push('');
      push(`${cleanReportText(layer.layer_name)} — ${layer.status}`);
      push(`  Function: ${cleanReportText(layer.function)}`);
      push(`  Revision note: ${cleanReportText(layer.revision_note)}`);
    });
  }

  if (Array.isArray(dream.arc_map) && dream.arc_map.length > 0) {
    push('');
    push(sub);
    push('ARC MAP');
    push(sub);
    dream.arc_map.forEach((act) => {
      push('');
      push(`${cleanReportText(act.act_name)} (${cleanReportText(act.chapter_range)})`);
      push(`  Function: ${cleanReportText(act.primary_function)}`);
      push(`  Revision priority: ${cleanReportText(act.revision_priority)}`);
    });
  }

  if (Array.isArray(dream.criterion_analyses) && dream.criterion_analyses.length > 0) {
    push('');
    push(sub);
    push('EXPANDED CRITERION ANALYSIS');
    push(sub);
    dream.criterion_analyses.forEach((a) => {
      push('');
      push(`${a.key} — ${a.score}/10 (${a.confidence} confidence)`);
      if (Array.isArray(a.fit_evidence) && a.fit_evidence.length > 0) push(`  What is working: ${a.fit_evidence.map((item) => cleanReportText(item)).join('; ')}`);
      if (Array.isArray(a.gap_evidence) && a.gap_evidence.length > 0) push(`  What weakens impact: ${a.gap_evidence.map((item) => cleanReportText(item)).join('; ')}`);
      if (Array.isArray(a.revision_queue) && a.revision_queue.length > 0) push(`  Revision queue: ${a.revision_queue.map((item) => cleanReportText(item)).join('; ')}`);
    });
  }

  if (Array.isArray(dream.revision_plan) && dream.revision_plan.length > 0) {
    push('');
    push(sub);
    push('REVISION PLAN');
    push(sub);
    dream.revision_plan.forEach((item) => {
      push('');
      push(`Priority ${item.priority}: ${cleanReportText(item.title)}`);
      push(`  Goal: ${cleanReportText(item.goal)}`);
      if (Array.isArray(item.actions) && item.actions.length > 0) push(`  Actions: ${item.actions.map((action) => cleanReportText(action)).join('; ')}`);
      if (item.acceptance_check) push(`  Acceptance check: ${cleanReportText(item.acceptance_check)}`);
    });
  }
}

function buildTxtReport(result: ExportableResult, title: string | null, jobId: string, dream: LongformDreamDocument | null): string {
  const lines: string[] = [];
  const sep = '='.repeat(72);
  const sub = '-'.repeat(72);
  const metadata = buildMetadata(result, title, dream);
  const summaryFallback = buildSummaryFallback(result);

  lines.push(sep);
  lines.push('REVISIONGRADE™ EVALUATION REPORT');
  lines.push(sep);
  lines.push(`Manuscript Title: ${metadata.displayTitle}`);
  lines.push(`Report Type: ${metadata.reportType}`);
  if (metadata.genre) lines.push(`Genre: ${metadata.genre}`);
  if (metadata.shelf) lines.push(`Shelf: ${metadata.shelf}`);
  if (metadata.wordCount) lines.push(`Submitted Word Count: ${metadata.wordCount.toLocaleString()}`);
  if (metadata.estimatedPages) lines.push(`Estimated Manuscript Pages: ${metadata.estimatedPages.toLocaleString()} at ${WORDS_PER_MANUSCRIPT_PAGE} words/page`);
  lines.push(`Generated: ${metadata.generatedAt}`);
  lines.push(`Overall Score: ${metadata.score}`);
  lines.push(`Verdict: ${metadata.verdict}`);
  lines.push('Confidentiality: Prepared for author/editorial use.');
  lines.push('');

  lines.push(sub);
  lines.push('SUMMARY');
  lines.push(sub);
  lines.push(cleanReportText(result.overview.one_paragraph_summary, summaryFallback, { blockTruncation: true }));
  lines.push('');

  lines.push(sub);
  lines.push('TOP STRENGTHS');
  lines.push(sub);
  result.overview.top_3_strengths.forEach((s, i) => lines.push(`${i + 1}. ${cleanReportText(s)}`));
  lines.push('');

  lines.push(sub);
  lines.push('TOP RISKS');
  lines.push(sub);
  result.overview.top_3_risks.forEach((r, i) => lines.push(`${i + 1}. ${cleanReportText(r)}`));
  lines.push('');

  lines.push(sub);
  lines.push('CRITERIA SCORES');
  lines.push(sub);
  result.criteria.forEach((c) => {
    lines.push(`• ${c.key} — ${scoreLabel(c.score_0_10, 10)}${c.confidence_level ? ` (${c.confidence_level} confidence)` : ''}`);
    if (c.rationale) lines.push(`  Rationale: ${cleanReportText(c.rationale)}`);
    lines.push('');
  });

  lines.push(sub);
  lines.push('QUICK WINS');
  lines.push(sub);
  if (result.recommendations.quick_wins.length === 0) lines.push('(none)');
  result.recommendations.quick_wins.forEach((qw, i) => {
    lines.push(`${i + 1}. ${cleanReportText(qw.action)} [effort: ${qw.effort}, impact: ${qw.impact}]`);
    if (qw.why) lines.push(`   Why: ${cleanReportText(qw.why)}`);
  });
  lines.push('');

  lines.push(sub);
  lines.push('STRATEGIC REVISIONS');
  lines.push(sub);
  if (result.recommendations.strategic_revisions.length === 0) lines.push('(none)');
  result.recommendations.strategic_revisions.forEach((sr, i) => {
    lines.push(`${i + 1}. ${cleanReportText(sr.action)} [effort: ${sr.effort}, impact: ${sr.impact}]`);
    if (sr.why) lines.push(`   Why: ${cleanReportText(sr.why)}`);
  });

  if (dream) appendDreamTxtSections(lines, dream);

  lines.push('');
  lines.push(sub);
  lines.push('TECHNICAL METADATA');
  lines.push(sub);
  lines.push(`Job ID: ${jobId}`);
  lines.push(`Schema: ${result.schema_version}`);
  lines.push('');
  lines.push(sep);
  lines.push(EXPORT_DISCLAIMER);
  return lines.join('\n');
}

function verdictColors(verdict: string): { bg: string; text: string } {
  const v = verdict.toLowerCase();
  if (v === 'pass') return { bg: RG.successBg, text: RG.success };
  if (v === 'revise') return { bg: RG.warningBg, text: RG.warning };
  return { bg: RG.errorBg, text: RG.error };
}

function confidenceColor(level: string | undefined): string {
  if (level === 'high') return RG.success;
  if (level === 'moderate') return RG.warning;
  if (level === 'low') return RG.error;
  return RG.textMuted;
}

function scoreBarColor(score: number | null | undefined): string {
  if (typeof score !== 'number') return RG.textFaint;
  if (score >= 8) return RG.success;
  if (score >= 6) return RG.warning;
  return RG.error;
}

async function buildPdfReport(result: ExportableResult, title: string | null, jobId: string, dream: LongformDreamDocument | null): Promise<Buffer> {
  return await new Promise<Buffer>((resolve, reject) => {
    const metadata = buildMetadata(result, title, dream);
    const summaryFallback = buildSummaryFallback(result);
    const doc = new PDFDocument({ size: 'LETTER', margin: 54, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer | Uint8Array) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const ml = doc.page.margins.left;
    const contentWidth = doc.page.width - ml - doc.page.margins.right;
    const bottomY = () => doc.page.height - doc.page.margins.bottom - 48;
    const ensureSpace = (height = 90) => {
      if (doc.y + height > bottomY()) doc.addPage();
    };

    // ── Branded helpers ───────────────────────────────────────────────
    const goldRule = () => {
      doc.moveTo(ml, doc.y).lineTo(ml + contentWidth, doc.y).strokeColor(RG.gold).lineWidth(1.5).stroke();
      doc.strokeColor('#000000').lineWidth(1);
      doc.moveDown(0.4);
    };
    const thinRule = () => {
      doc.moveTo(ml, doc.y).lineTo(ml + contentWidth, doc.y).strokeColor(RG.border).lineWidth(0.5).stroke();
      doc.strokeColor('#000000').lineWidth(1);
      doc.moveDown(0.3);
    };
    const section = (text: unknown) => {
      ensureSpace(72);
      doc.moveDown(0.8);
      doc.font('Helvetica-Bold').fontSize(14).fillColor(RG.oxblood).text(toPdfSafeText(text), { width: contentWidth });
      doc.moveDown(0.25);
      goldRule();
    };
    const paragraph = (text: unknown) => {
      ensureSpace(70);
      doc.font('Helvetica').fontSize(10.5).fillColor(RG.textPrimary).text(toPdfSafeText(text), { width: contentWidth, lineGap: 3 });
      doc.moveDown(0.45);
    };
    const bullet = (text: unknown, color: string = RG.textPrimary) => {
      ensureSpace(45);
      doc.font('Helvetica').fontSize(10.5).fillColor(color).text(`  -  ${toPdfSafeText(text)}`, { width: contentWidth, indent: 8, lineGap: 2 });
      doc.moveDown(0.25);
    };
    const labelValue = (label: string, value: unknown) => {
      const safeValue = toPdfSafeText(value, '');
      if (!safeValue) return;
      doc.font('Helvetica-Bold').fontSize(10).fillColor(RG.textMuted).text(`${toPdfSafeText(label)}:  `, { continued: true });
      doc.font('Helvetica').fillColor(RG.textPrimary).text(safeValue, { width: contentWidth });
      doc.moveDown(0.2);
    };

    // ── Cover page ────────────────────────────────────────────────────
    // Top gold accent bar
    doc.rect(0, 0, doc.page.width, 6).fill(RG.gold);

    doc.moveDown(2.5);
    doc.font('Helvetica-Bold').fontSize(28).fillColor(RG.oxblood).text(
      toPdfSafeText('RevisionGrade(TM)'),
      { width: contentWidth, align: 'center' },
    );
    doc.moveDown(0.15);
    doc.font('Helvetica').fontSize(10).fillColor(RG.textMuted).text(
      'Manuscript diagnosis, author-controlled revision, and professional submission preparation.',
      { width: contentWidth, align: 'center' },
    );
    doc.moveDown(1.5);
    goldRule();
    doc.moveDown(0.5);

    // Title
    doc.font('Helvetica-Bold').fontSize(20).fillColor(RG.textPrimary).text(
      toPdfSafeText(metadata.displayTitle),
      { width: contentWidth, align: 'center' },
    );
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(11).fillColor(RG.textMuted).text(
      metadata.reportType,
      { width: contentWidth, align: 'center' },
    );
    doc.moveDown(1.5);

    // Score + Verdict block
    const vColors = verdictColors(metadata.verdict);
    const scoreNum = result.overview.overall_score_0_100;
    // Score circle area
    const circleX = ml + contentWidth / 2;
    const circleY = doc.y + 36;
    doc.circle(circleX, circleY, 34).fillAndStroke(RG.surface, RG.gold);
    doc.font('Helvetica-Bold').fontSize(26).fillColor(RG.textPrimary).text(
      `${Math.round(scoreNum)}`,
      circleX - 30, circleY - 16,
      { width: 60, align: 'center' },
    );
    doc.font('Helvetica').fontSize(8).fillColor(RG.textMuted).text(
      'out of 100',
      circleX - 30, circleY + 12,
      { width: 60, align: 'center' },
    );
    doc.y = circleY + 46;

    // Verdict badge
    doc.moveDown(0.5);
    const badgeWidth = 100;
    const badgeX = circleX - badgeWidth / 2;
    doc.roundedRect(badgeX, doc.y, badgeWidth, 22, 4).fill(vColors.bg);
    doc.font('Helvetica-Bold').fontSize(11).fillColor(vColors.text).text(
      metadata.verdict,
      badgeX, doc.y + 5,
      { width: badgeWidth, align: 'center' },
    );
    doc.y += 32;
    doc.moveDown(1.2);

    // Metadata block
    thinRule();
    doc.moveDown(0.3);
    labelValue('Genre', metadata.genre);
    labelValue('Shelf', metadata.shelf);
    labelValue('Submitted Word Count', metadata.wordCount ? metadata.wordCount.toLocaleString() : null);
    labelValue('Estimated Manuscript Pages', metadata.estimatedPages ? `${metadata.estimatedPages.toLocaleString()} at ${WORDS_PER_MANUSCRIPT_PAGE} words/page` : null);
    labelValue('Generated', metadata.generatedAt);
    labelValue('Confidentiality', 'Prepared for author/editorial use');
    doc.moveDown(1.5);

    // Bottom gold accent bar on cover
    thinRule();
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(8.5).fillColor(RG.textFaint).text(
      toPdfSafeText(EXPORT_DISCLAIMER),
      { width: contentWidth, align: 'center' },
    );

    // ── Page 2+: Report content ───────────────────────────────────────
    doc.addPage();

    section('Executive Summary');
    paragraph(cleanReportText(result.overview.one_paragraph_summary, summaryFallback, { blockTruncation: true }));

    // Strengths & Risks side by side concept (rendered sequentially for pdfkit)
    section('Top Strengths');
    if (result.overview.top_3_strengths.length > 0) {
      result.overview.top_3_strengths.forEach((s) => bullet(s, RG.success));
    } else {
      paragraph('(none)');
    }

    section('Top Risks');
    if (result.overview.top_3_risks.length > 0) {
      result.overview.top_3_risks.forEach((r) => bullet(r, RG.warning));
    } else {
      paragraph('(none)');
    }

    // ── Criteria Scores with visual bars ──────────────────────────────
    section('Criteria Scores');
    result.criteria.forEach((c) => {
      ensureSpace(100);
      const score = c.score_0_10;
      const barColor = scoreBarColor(score);
      const confColor = confidenceColor(c.confidence_level);

      // Criterion name + score
      doc.font('Helvetica-Bold').fontSize(11).fillColor(RG.textPrimary).text(
        toPdfSafeText(c.key),
        ml, doc.y,
        { width: contentWidth - 80, continued: false },
      );
      // Score on the right
      const scoreY = doc.y - 14;
      doc.font('Helvetica-Bold').fontSize(13).fillColor(barColor).text(
        scoreLabel(score, 10),
        ml + contentWidth - 70, scoreY,
        { width: 70, align: 'right' },
      );
      doc.y = Math.max(doc.y, scoreY + 16);

      // Score bar
      const barY = doc.y;
      const barWidth = contentWidth - 90;
      const barHeight = 6;
      // Background bar
      doc.roundedRect(ml, barY, barWidth, barHeight, 3).fill(RG.border);
      // Filled bar
      if (typeof score === 'number' && score > 0) {
        const fillWidth = Math.max(6, (score / 10) * barWidth);
        doc.roundedRect(ml, barY, fillWidth, barHeight, 3).fill(barColor);
      }
      // Confidence label
      if (c.confidence_level) {
        doc.font('Helvetica').fontSize(8).fillColor(confColor).text(
          `${c.confidence_level} confidence`,
          ml + barWidth + 8, barY - 1,
          { width: 80 },
        );
      }
      doc.y = barY + barHeight + 6;

      // Rationale
      if (c.rationale) {
        doc.font('Helvetica').fontSize(9.5).fillColor(RG.textMuted).text(
          toPdfSafeText(c.rationale),
          ml + 4, doc.y,
          { width: contentWidth - 8, lineGap: 2 },
        );
      }
      doc.moveDown(0.6);
      thinRule();
    });

    // ── Quick Wins ────────────────────────────────────────────────────
    section('Quick Wins');
    if (result.recommendations.quick_wins.length === 0) {
      paragraph('(none identified)');
    } else {
      result.recommendations.quick_wins.forEach((qw, idx) => {
        ensureSpace(85);
        doc.font('Helvetica-Bold').fontSize(10.5).fillColor(RG.textPrimary).text(
          toPdfSafeText(`${idx + 1}. ${cleanReportText(qw.action)}`),
          { width: contentWidth },
        );
        // Effort/impact pills
        doc.font('Helvetica').fontSize(8.5).fillColor(RG.textMuted).text(
          `Effort: ${qw.effort}  |  Impact: ${qw.impact}`,
          { width: contentWidth },
        );
        if (qw.why) {
          doc.moveDown(0.15);
          doc.font('Helvetica').fontSize(9.5).fillColor(RG.textMuted).text(
            toPdfSafeText(qw.why),
            ml + 12, doc.y,
            { width: contentWidth - 16, lineGap: 2 },
          );
        }
        doc.moveDown(0.5);
      });
    }

    // ── Strategic Revisions ───────────────────────────────────────────
    section('Strategic Revisions');
    if (result.recommendations.strategic_revisions.length === 0) {
      paragraph('(none identified)');
    } else {
      result.recommendations.strategic_revisions.forEach((sr, idx) => {
        ensureSpace(85);
        doc.font('Helvetica-Bold').fontSize(10.5).fillColor(RG.textPrimary).text(
          toPdfSafeText(`${idx + 1}. ${cleanReportText(sr.action)}`),
          { width: contentWidth },
        );
        doc.font('Helvetica').fontSize(8.5).fillColor(RG.textMuted).text(
          `Effort: ${sr.effort}  |  Impact: ${sr.impact}`,
          { width: contentWidth },
        );
        if (sr.why) {
          doc.moveDown(0.15);
          doc.font('Helvetica').fontSize(9.5).fillColor(RG.textMuted).text(
            toPdfSafeText(sr.why),
            ml + 12, doc.y,
            { width: contentWidth - 16, lineGap: 2 },
          );
        }
        doc.moveDown(0.5);
      });
    }

    // ── Dream / Narrative Synthesis (longform) ────────────────────────
    if (dream) {
      section('Narrative Synthesis');
      // Dream scores row
      ensureSpace(60);
      const dreamLabels = ['Quality', 'Readiness', 'Commercial', 'Literary'];
      const dreamScores = [
        dream.dream_scores?.quality,
        dream.dream_scores?.readiness,
        dream.dream_scores?.commercial,
        dream.dream_scores?.literary,
      ];
      const colW = contentWidth / 4;
      const rowY = doc.y;
      dreamLabels.forEach((label, i) => {
        const x = ml + i * colW;
        const val = dreamScores[i];
        doc.font('Helvetica').fontSize(8).fillColor(RG.textMuted).text(label, x, rowY, { width: colW, align: 'center' });
        doc.font('Helvetica-Bold').fontSize(16).fillColor(RG.textPrimary).text(
          `${val ?? '-'}`,
          x, rowY + 12,
          { width: colW, align: 'center' },
        );
        doc.font('Helvetica').fontSize(7).fillColor(RG.textFaint).text('/100', x, rowY + 30, { width: colW, align: 'center' });
      });
      doc.y = rowY + 44;
      doc.moveDown(0.5);
      thinRule();

      doc.font('Helvetica-Bold').fontSize(12).fillColor(RG.oxblood).text('Executive Verdict', { width: contentWidth });
      doc.moveDown(0.2);
      paragraph(dream.executive_verdict);

      if (dream.market_shelf) {
        section('Market Shelf');
        labelValue('Best Shelf', dream.market_shelf.best_shelf);
        labelValue('Marketable Hook', dream.market_shelf.marketable_hook);
        labelValue('Market Danger', dream.market_shelf.market_danger);
      }

      if (Array.isArray(dream.structural_stack) && dream.structural_stack.length > 0) {
        section('Structural Stack');
        dream.structural_stack.forEach((layer) => {
          ensureSpace(90);
          doc.font('Helvetica-Bold').fontSize(10.5).fillColor(RG.textPrimary).text(
            toPdfSafeText(`${cleanReportText(layer.layer_name)} -- ${layer.status}`),
            { width: contentWidth },
          );
          paragraph(`Function: ${cleanReportText(layer.function)}`);
          paragraph(`Revision note: ${cleanReportText(layer.revision_note)}`);
        });
      }

      if (Array.isArray(dream.arc_map) && dream.arc_map.length > 0) {
        section('Arc Map');
        dream.arc_map.forEach((act) => {
          ensureSpace(80);
          doc.font('Helvetica-Bold').fontSize(10.5).fillColor(RG.textPrimary).text(
            toPdfSafeText(`${cleanReportText(act.act_name)} (${cleanReportText(act.chapter_range)})`),
            { width: contentWidth },
          );
          paragraph(`Function: ${cleanReportText(act.primary_function)}`);
          paragraph(`Revision priority: ${cleanReportText(act.revision_priority)}`);
        });
      }

      if (Array.isArray(dream.revision_plan) && dream.revision_plan.length > 0) {
        section('Revision Plan');
        dream.revision_plan.forEach((item) => {
          ensureSpace(90);
          doc.font('Helvetica-Bold').fontSize(10.5).fillColor(RG.textPrimary).text(
            toPdfSafeText(`Priority ${item.priority}: ${cleanReportText(item.title)}`),
            { width: contentWidth },
          );
          paragraph(`Goal: ${cleanReportText(item.goal)}`);
          if (Array.isArray(item.actions) && item.actions.length > 0) item.actions.forEach((a) => bullet(a));
          if (item.acceptance_check) paragraph(`Acceptance check: ${cleanReportText(item.acceptance_check)}`);
        });
      }
    }

    // ── Technical Metadata ────────────────────────────────────────────
    section('Technical Metadata');
    labelValue('Job ID', jobId);
    labelValue('Schema', result.schema_version);

    // ── Branded footers on every page ─────────────────────────────────
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i += 1) {
      doc.switchToPage(i);
      const pageNumber = i - range.start + 1;
      const footerY = doc.page.height - 40;

      // Gold line above footer
      doc.moveTo(ml, footerY - 8).lineTo(ml + contentWidth, footerY - 8)
        .strokeColor(RG.gold).lineWidth(0.5).stroke();
      doc.strokeColor('#000000').lineWidth(1);

      if (pageNumber === 1) {
        doc.font('Helvetica').fontSize(7).fillColor(RG.textFaint).text(
          toPdfSafeText(FOOTER_LINE),
          ml, footerY,
          { width: contentWidth, align: 'center' },
        );
      } else {
        doc.font('Helvetica').fontSize(7).fillColor(RG.textFaint).text(
          toPdfSafeText(`RevisionGrade(TM) Evaluation Report  --  Confidential  --  Page ${pageNumber}`),
          ml, footerY,
          { width: contentWidth, align: 'center' },
        );
      }
      doc.fillColor('#000000');
    }

    doc.end();
  });
}

function docxVerdictColor(verdict: string): string {
  const v = verdict.toLowerCase();
  if (v === 'pass') return RG.success;
  if (v === 'revise') return RG.warning;
  return RG.error;
}

function docxScoreColor(score: number | null | undefined): string {
  if (typeof score !== 'number') return RG.textFaint;
  if (score >= 8) return RG.success;
  if (score >= 6) return RG.warning;
  return RG.error;
}

const DOCX_NONE_BORDER = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
const DOCX_NO_BORDERS = { top: DOCX_NONE_BORDER, bottom: DOCX_NONE_BORDER, left: DOCX_NONE_BORDER, right: DOCX_NONE_BORDER };

async function buildDocx(result: ExportableResult, title: string | null, jobId: string, dream: LongformDreamDocument | null): Promise<Buffer> {
  const metadata = buildMetadata(result, title, dream);
  const summaryFallback = buildSummaryFallback(result);

  const spacer = () => new Paragraph({ spacing: { after: 120 }, children: [] });
  const brandHeading = (text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel]) =>
    new Paragraph({
      heading: level,
      spacing: { before: 240, after: 80 },
      children: [new TextRun({ text, color: RG.oxblood.replace('#', ''), bold: true })],
    });
  const bodyPara = (text: string, opts: { bold?: boolean; color?: string; size?: number; spacing?: number } = {}) =>
    new Paragraph({
      spacing: { after: opts.spacing ?? 100 },
      children: [new TextRun({
        text: cleanReportText(text),
        bold: opts.bold ?? false,
        size: opts.size ?? 21,
        color: (opts.color ?? RG.textPrimary).replace('#', ''),
        font: 'Calibri',
      })],
    });
  const bulletPara = (text: string, color?: string) =>
    new Paragraph({
      spacing: { after: 60 },
      children: [new TextRun({
        text: `  \u2022  ${cleanReportText(text)}`,
        size: 21,
        color: (color ?? RG.textPrimary).replace('#', ''),
        font: 'Calibri',
      })],
    });
  const metaRow = (label: string, value: string | null) => {
    if (!value) return null;
    return new Paragraph({
      spacing: { after: 40 },
      children: [
        new TextRun({ text: `${label}: `, bold: true, size: 20, color: RG.textMuted.replace('#', ''), font: 'Calibri' }),
        new TextRun({ text: value, size: 20, color: RG.textPrimary.replace('#', ''), font: 'Calibri' }),
      ],
    });
  };

  const children: (Paragraph | Table)[] = [];

  // ── Cover page ──────────────────────────────────────────────────
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 40 },
    children: [new TextRun({ text: 'RevisionGrade\u2122', bold: true, size: 52, color: RG.oxblood.replace('#', ''), font: 'Georgia' })],
  }));
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
    children: [new TextRun({
      text: 'Manuscript diagnosis, author-controlled revision, and professional submission preparation.',
      size: 19, color: RG.textMuted.replace('#', ''), font: 'Calibri', italics: true,
    })],
  }));

  // Gold divider via table
  children.push(new Table({
    rows: [new TableRow({
      children: [new TableCell({
        width: { size: 100, type: WidthType.PERCENTAGE },
        borders: DOCX_NO_BORDERS,
        shading: { type: ShadingType.SOLID, color: RG.gold.replace('#', '') },
        children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: ' ', size: 4 })] })],
      })],
    })],
    width: { size: 100, type: WidthType.PERCENTAGE },
  }));
  children.push(spacer());

  // Title
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 80 },
    children: [new TextRun({ text: metadata.displayTitle, bold: true, size: 36, color: RG.textPrimary.replace('#', ''), font: 'Georgia' })],
  }));
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 160 },
    children: [new TextRun({ text: metadata.reportType, size: 22, color: RG.textMuted.replace('#', ''), font: 'Calibri' })],
  }));

  // Score + Verdict table
  const verdictCol = docxVerdictColor(metadata.verdict);
  children.push(new Table({
    rows: [new TableRow({
      children: [
        new TableCell({
          width: { size: 50, type: WidthType.PERCENTAGE },
          borders: DOCX_NO_BORDERS,
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({ text: `${Math.round(result.overview.overall_score_0_100)}`, bold: true, size: 56, color: RG.textPrimary.replace('#', ''), font: 'Georgia' }),
              new TextRun({ text: ' / 100', size: 22, color: RG.textMuted.replace('#', ''), font: 'Calibri' }),
            ],
          })],
        }),
        new TableCell({
          width: { size: 50, type: WidthType.PERCENTAGE },
          borders: DOCX_NO_BORDERS,
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: metadata.verdict, bold: true, size: 36, color: verdictCol.replace('#', ''), font: 'Georgia' })],
          })],
        }),
      ],
    })],
    width: { size: 100, type: WidthType.PERCENTAGE },
  }));
  children.push(spacer());

  // Metadata block
  const metaLines = [
    metaRow('Genre', metadata.genre),
    metaRow('Shelf', metadata.shelf),
    metaRow('Submitted Word Count', metadata.wordCount ? metadata.wordCount.toLocaleString() : null),
    metaRow('Estimated Manuscript Pages', metadata.estimatedPages ? `${metadata.estimatedPages.toLocaleString()} at ${WORDS_PER_MANUSCRIPT_PAGE} words/page` : null),
    metaRow('Generated', metadata.generatedAt),
    metaRow('Confidentiality', 'Prepared for author/editorial use'),
  ].filter((p): p is Paragraph => p !== null);
  metaLines.forEach((p) => children.push(p));
  children.push(spacer());

  // ── Summary ─────────────────────────────────────────────────────
  children.push(brandHeading('Executive Summary', HeadingLevel.HEADING_2));
  children.push(bodyPara(cleanReportText(result.overview.one_paragraph_summary, summaryFallback, { blockTruncation: true })));

  // ── Strengths & Risks ───────────────────────────────────────────
  children.push(brandHeading('Top Strengths', HeadingLevel.HEADING_2));
  result.overview.top_3_strengths.forEach((s) => children.push(bulletPara(s, RG.success)));

  children.push(brandHeading('Top Risks', HeadingLevel.HEADING_2));
  result.overview.top_3_risks.forEach((r) => children.push(bulletPara(r, RG.warning)));

  // ── Criteria Score Table ────────────────────────────────────────
  children.push(brandHeading('Criteria Scores', HeadingLevel.HEADING_2));
  // Header row
  const headerRow = new TableRow({
    children: [
      new TableCell({
        width: { size: 45, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: RG.ink.replace('#', '') },
        borders: DOCX_NO_BORDERS,
        children: [new Paragraph({ children: [new TextRun({ text: 'Criterion', bold: true, size: 19, color: RG.cream.replace('#', ''), font: 'Calibri' })] })],
      }),
      new TableCell({
        width: { size: 15, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: RG.ink.replace('#', '') },
        borders: DOCX_NO_BORDERS,
        children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Score', bold: true, size: 19, color: RG.cream.replace('#', ''), font: 'Calibri' })] })],
      }),
      new TableCell({
        width: { size: 40, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: RG.ink.replace('#', '') },
        borders: DOCX_NO_BORDERS,
        children: [new Paragraph({ children: [new TextRun({ text: 'Confidence', bold: true, size: 19, color: RG.cream.replace('#', ''), font: 'Calibri' })] })],
      }),
    ],
  });

  const criteriaRows = result.criteria.map((c, idx) => {
    const rowShading = idx % 2 === 0 ? RG.surface.replace('#', '') : RG.surfaceAlt.replace('#', '');
    const sColor = docxScoreColor(c.score_0_10);
    const confStr = c.confidence_level ? `${c.confidence_level}` : '-';
    return new TableRow({
      children: [
        new TableCell({
          shading: { type: ShadingType.SOLID, color: rowShading },
          borders: DOCX_NO_BORDERS,
          children: [new Paragraph({ children: [new TextRun({ text: c.key, size: 20, color: RG.textPrimary.replace('#', ''), font: 'Calibri' })] })],
        }),
        new TableCell({
          shading: { type: ShadingType.SOLID, color: rowShading },
          borders: DOCX_NO_BORDERS,
          children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: scoreLabel(c.score_0_10, 10), bold: true, size: 20, color: sColor.replace('#', ''), font: 'Calibri' })] })],
        }),
        new TableCell({
          shading: { type: ShadingType.SOLID, color: rowShading },
          borders: DOCX_NO_BORDERS,
          children: [new Paragraph({ children: [new TextRun({ text: confStr, size: 20, color: confidenceColor(c.confidence_level).replace('#', ''), font: 'Calibri' })] })],
        }),
      ],
    });
  });

  children.push(new Table({
    rows: [headerRow, ...criteriaRows],
    width: { size: 100, type: WidthType.PERCENTAGE },
  }));
  children.push(spacer());

  // Rationales
  result.criteria.forEach((c) => {
    if (!c.rationale) return;
    children.push(bodyPara(`${c.key}: ${c.rationale}`, { size: 19, color: RG.textMuted }));
  });

  // ── Quick Wins ──────────────────────────────────────────────────
  children.push(brandHeading('Quick Wins', HeadingLevel.HEADING_2));
  if (result.recommendations.quick_wins.length === 0) {
    children.push(bodyPara('(none identified)'));
  } else {
    result.recommendations.quick_wins.forEach((qw, idx) => {
      children.push(bodyPara(`${idx + 1}. ${cleanReportText(qw.action)}`, { bold: true }));
      children.push(bodyPara(`Effort: ${qw.effort}  |  Impact: ${qw.impact}`, { size: 18, color: RG.textMuted, spacing: 40 }));
      if (qw.why) children.push(bodyPara(`${cleanReportText(qw.why)}`, { size: 19, color: RG.textMuted }));
    });
  }

  // ── Strategic Revisions ─────────────────────────────────────────
  children.push(brandHeading('Strategic Revisions', HeadingLevel.HEADING_2));
  if (result.recommendations.strategic_revisions.length === 0) {
    children.push(bodyPara('(none identified)'));
  } else {
    result.recommendations.strategic_revisions.forEach((sr, idx) => {
      children.push(bodyPara(`${idx + 1}. ${cleanReportText(sr.action)}`, { bold: true }));
      children.push(bodyPara(`Effort: ${sr.effort}  |  Impact: ${sr.impact}`, { size: 18, color: RG.textMuted, spacing: 40 }));
      if (sr.why) children.push(bodyPara(`${cleanReportText(sr.why)}`, { size: 19, color: RG.textMuted }));
    });
  }

  // ── Dream / Narrative Synthesis ─────────────────────────────────
  if (dream) {
    children.push(brandHeading('Narrative Synthesis', HeadingLevel.HEADING_2));
    // Dream scores table
    const dreamScoreRow = new TableRow({
      children: ['Quality', 'Readiness', 'Commercial', 'Literary'].map((label, i) => {
        const vals = [dream.dream_scores?.quality, dream.dream_scores?.readiness, dream.dream_scores?.commercial, dream.dream_scores?.literary];
        return new TableCell({
          width: { size: 25, type: WidthType.PERCENTAGE },
          borders: DOCX_NO_BORDERS,
          shading: { type: ShadingType.SOLID, color: RG.surface.replace('#', '') },
          children: [
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: label, size: 17, color: RG.textMuted.replace('#', ''), font: 'Calibri' })] }),
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: `${vals[i] ?? '-'}/100`, bold: true, size: 24, color: RG.textPrimary.replace('#', ''), font: 'Georgia' })] }),
          ],
        });
      }),
    });
    children.push(new Table({ rows: [dreamScoreRow], width: { size: 100, type: WidthType.PERCENTAGE } }));
    children.push(spacer());

    children.push(brandHeading('Executive Verdict', HeadingLevel.HEADING_3));
    children.push(bodyPara(dream.executive_verdict ?? '-'));

    if (dream.market_shelf) {
      children.push(brandHeading('Market Shelf', HeadingLevel.HEADING_3));
      const shelfMeta = [
        metaRow('Best Shelf', dream.market_shelf.best_shelf),
        metaRow('Marketable Hook', dream.market_shelf.marketable_hook),
        metaRow('Market Danger', dream.market_shelf.market_danger),
      ].filter((p): p is Paragraph => p !== null);
      shelfMeta.forEach((p) => children.push(p));
      if (Array.isArray(dream.market_shelf.shelf_neighbors)) {
        dream.market_shelf.shelf_neighbors.forEach((item) => children.push(bulletPara(item)));
      }
    }

    if (Array.isArray(dream.structural_stack) && dream.structural_stack.length > 0) {
      children.push(brandHeading('Structural Stack', HeadingLevel.HEADING_3));
      dream.structural_stack.forEach((layer) => {
        children.push(bodyPara(`${layer.layer_name} - ${layer.status}`, { bold: true }));
        children.push(bodyPara(`Function: ${layer.function}`, { size: 19, color: RG.textMuted }));
        children.push(bodyPara(`Revision note: ${layer.revision_note}`, { size: 19, color: RG.textMuted }));
      });
    }

    if (Array.isArray(dream.arc_map) && dream.arc_map.length > 0) {
      children.push(brandHeading('Arc Map', HeadingLevel.HEADING_3));
      dream.arc_map.forEach((act) => {
        children.push(bodyPara(`${act.act_name} (${act.chapter_range})`, { bold: true }));
        children.push(bodyPara(`Function: ${act.primary_function}`, { size: 19, color: RG.textMuted }));
        children.push(bodyPara(`Revision priority: ${act.revision_priority}`, { size: 19, color: RG.textMuted }));
      });
    }

    if (Array.isArray(dream.revision_plan) && dream.revision_plan.length > 0) {
      children.push(brandHeading('Revision Plan', HeadingLevel.HEADING_3));
      dream.revision_plan.forEach((item) => {
        children.push(bodyPara(`Priority ${item.priority}: ${item.title}`, { bold: true }));
        children.push(bodyPara(`Goal: ${item.goal}`, { size: 19, color: RG.textMuted }));
        if (Array.isArray(item.actions)) item.actions.forEach((action) => children.push(bulletPara(action)));
        if (item.acceptance_check) children.push(bodyPara(`Acceptance check: ${item.acceptance_check}`, { size: 19, color: RG.textMuted }));
      });
    }
  }

  // ── Technical Metadata ──────────────────────────────────────────
  children.push(brandHeading('Technical Metadata', HeadingLevel.HEADING_2));
  const techMeta = [metaRow('Job ID', jobId), metaRow('Schema', result.schema_version)].filter((p): p is Paragraph => p !== null);
  techMeta.forEach((p) => children.push(p));
  children.push(spacer());

  // Gold divider
  children.push(new Table({
    rows: [new TableRow({
      children: [new TableCell({
        width: { size: 100, type: WidthType.PERCENTAGE },
        borders: DOCX_NO_BORDERS,
        shading: { type: ShadingType.SOLID, color: RG.gold.replace('#', '') },
        children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: ' ', size: 4 })] })],
      })],
    })],
    width: { size: 100, type: WidthType.PERCENTAGE },
  }));
  children.push(bodyPara(EXPORT_DISCLAIMER, { size: 16, color: RG.textFaint, spacing: 40 }));

  const docxDoc = new Document({
    sections: [{
      headers: {
        default: new Header({
          children: [new Paragraph({
            alignment: AlignmentType.RIGHT,
            children: [new TextRun({ text: 'RevisionGrade\u2122 Evaluation Report', size: 16, color: RG.textFaint.replace('#', ''), font: 'Calibri', italics: true })],
          })],
        }),
      },
      footers: {
        default: new Footer({
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({ text: 'RevisionGrade\u2122  |  Confidential  |  Page ', size: 14, color: RG.textFaint.replace('#', ''), font: 'Calibri' }),
              new TextRun({ children: [PageNumber.CURRENT], size: 14, color: RG.textFaint.replace('#', ''), font: 'Calibri' }),
            ],
          })],
        }),
      },
      children,
    }],
  });
  return await Packer.toBuffer(docxDoc);
}

async function loadCanonicalEvaluationResult(admin: ReturnType<typeof createAdminClient>, jobId: string): Promise<unknown | null> {
  const { data: artifact } = await admin
    .from('evaluation_artifacts')
    .select('content')
    .eq('job_id', jobId)
    .in('artifact_type', ['evaluation_result_v2', 'evaluation_result_v1'])
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  return artifact?.content ?? null;
}

async function loadDreamDocument(admin: ReturnType<typeof createAdminClient>, jobId: string): Promise<LongformDreamDocument | null> {
  const { data: dreamRow } = await admin
    .from('evaluation_artifacts')
    .select('content')
    .eq('job_id', jobId)
    .eq('artifact_type', 'longform_document_v1')
    .maybeSingle();
  const content = dreamRow?.content as { longform_document?: unknown } | null | undefined;
  if (content?.longform_document && typeof content.longform_document === 'object') {
    return content.longform_document as LongformDreamDocument;
  }
  return null;
}

export async function GET(
  request: NextRequest,
  { params }: { params: { jobId: string } | Promise<{ jobId: string }> },
) {
  const resolved = await Promise.resolve(params);
  const jobId = resolved.jobId;

  if (!jobId || !UUID_RE.test(jobId)) {
    return NextResponse.json({ error: 'Invalid job ID' }, { status: 400 });
  }

  const { searchParams } = new URL(request.url);
  const formatParam = (searchParams.get('format') ?? 'pdf').toLowerCase();
  if (!['pdf', 'docx', 'txt'].includes(formatParam)) {
    return NextResponse.json({ error: 'Invalid format' }, { status: 400 });
  }
  const format = formatParam as ExportFormat;

  const ssrSupabase = await createSSRClient();
  const {
    data: { user },
  } = await ssrSupabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const admin = createAdminClient();
  const { data: job, error } = await admin
    .from('evaluation_jobs')
    .select(`evaluation_result, status, validity_status, manuscripts!inner(user_id, title)`)
    .eq('id', jobId)
    .eq('manuscripts.user_id', user.id)
    .single();

  if (error || !job) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  const canonicalResult = await loadCanonicalEvaluationResult(admin, jobId);
  const rawResult = canonicalResult ?? (job.evaluation_result as unknown);

  if (!rawResult || !canReleaseEvaluationRead({ ...job, evaluation_result: rawResult })) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  if (!isExportableResultCandidate(rawResult)) {
    return NextResponse.json({ error: 'Invalid result format' }, { status: 500 });
  }

  const result = rawResult as ExportableResult;
  const relationTitle = extractManuscriptTitle((job as { manuscripts?: unknown }).manuscripts);
  const title = relationTitle ?? result.metrics?.manuscript?.title ?? null;
  const dream = await loadDreamDocument(admin, jobId);

  if (format === 'txt') {
    const body = buildTxtReport(result, title, jobId, dream);
    return new Response(body, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'txt')}"`,
        'Cache-Control': 'no-store',
      },
    });
  }

  if (format === 'pdf') {
    try {
      const buffer = await buildPdfReport(result, title, jobId, dream);
      return new Response(new Uint8Array(buffer), {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'pdf')}"`,
          'Cache-Control': 'no-store',
        },
      });
    } catch (err) {
      console.error('[report-download] PDF export failed', {
        jobId,
        error: err instanceof Error ? err.message : String(err),
        stack: err instanceof Error ? err.stack : undefined,
      });

      const body = buildTxtReport(result, title, jobId, dream);
      return new Response(body, {
        status: 200,
        headers: {
          'Content-Type': 'text/plain; charset=utf-8',
          'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'txt')}"`,
          'Cache-Control': 'no-store',
          'X-RevisionGrade-Export-Fallback': 'pdf-to-txt',
        },
      });
    }
  }

  const buffer = await buildDocx(result, title, jobId, dream);
  return new Response(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${safeFilename(title, jobId, 'docx')}"`,
      'Cache-Control': 'no-store',
    },
  });
}
