/**
 * RevisionGrade — Resources Page
 *
 * Route: /resources
 * Design language: ritual-luxury (rg-ink, rg-cream, rg-gold, rg-red)
 * Sections: Methodology · FAQs (Evaluate + Revise scoped) · Glossary
 *
 * Scope: Evaluate and Revise only — per launch-scope decision.
 * Dropped: Convert, Output, Storygate Studio content.
 */
import Link from "next/link";

export const metadata = {
  title: "Resources — RevisionGrade™",
  description:
    "Methodology, FAQs, and guidance for the RevisionGrade Evaluate and Revise workflow.",
};

const METHODOLOGY_SECTIONS = [
  {
    label: "The WAVE Revision System",
    body: `WAVE (Weighted Analysis Via Evaluation) is the underlying framework that powers every
    RevisionGrade evaluation. It applies a governed, deterministic reading of your manuscript against
    13 story evaluation criteria — producing consistent, repeatable results across every pass. WAVE is
    not a grammar checker, sentiment engine, or word predictor. It reads for structure, causality,
    character pressure, pacing, voice, and the other signals that govern whether a manuscript is
    publishable by industry standards.`,
  },
  {
    label: "The 13 Story Evaluation Criteria",
    body: `Each manuscript is scored independently across 13 criteria, including Spine & Causality,
    Character Pressure, Structural Pacing, Voice Integrity, Thematic Coherence, Scene Economy,
    Dialogue Authenticity, World Consistency, Emotional Resonance, and Market Readiness. Each
    criterion is scored 1–10, with a composite score calculated as a weighted average. A score of
    8.0 or higher meets the RevisionGrade threshold for agent-facing readiness.`,
  },
  {
    label: "MUST / SHOULD / COULD Severity",
    body: `Every revision opportunity generated by the WAVE framework is classified by severity and
    leverage. MUST issues are blocking craft problems that, if unresolved, prevent a manuscript from
    being submittable. SHOULD issues are significant weaknesses that will be noticed by a skilled
    agent or editor. COULD issues are refinements and polish. Severity is assigned deterministically
    — not by preference — based on the impact each issue has on the manuscript's core architecture
    and readability.`,
  },
  {
    label: "The REVISE Queue",
    body: `REVISE is the governed execution layer of RevisionGrade. It receives the structured
    RevisionOpportunity items produced by an evaluation and presents them in a severity-ordered queue.
    Authors may navigate by chapter or by criterion, accept or reject proposed revisions, enter custom
    text, or defer items. Every decision is saved to a durable revision session and can be restored
    on re-entry. The final revised manuscript is assembled from the saved decision record — not from
    ad hoc inline edits.`,
  },
  {
    label: "The DREAM Long-Form Report",
    body: `DREAM (Deep Revision Evaluation and Analysis for Manuscripts) is the full evaluation report
    format for novel-length manuscripts. It includes a chapter-by-chapter structural analysis, a
    criterion scorecard, MUST/SHOULD/COULD revision opportunity lists, an executive narrative summary,
    and an exportable agent-facing package. DREAM reports are generated from the same governed
    framework as all evaluations — not from generative summaries or marketing copy.`,
  },
  {
    label: "What RevisionGrade Is Not",
    body: `RevisionGrade is framework-driven analysis. It does not replace human editorial judgment,
    developmental editors, literary agents, or publication-decision authorities. It does not guarantee
    representation, publication, or commercial success. A score of 8.0 or higher means a manuscript
    meets the RevisionGrade framework threshold for agent-facing readiness — not that it will be
    accepted by any given agent or publisher. RevisionGrade is an instrument. The author and their
    trusted readers remain the final authorities on their work.`,
  },
];

const EVALUATE_FAQS = [
  {
    q: "What file formats does RevisionGrade accept?",
    a: "You can upload manuscripts in .txt, .docx, or .pdf format. For best results, use plain text or a clean .docx without tracked changes or heavy formatting.",
  },
  {
    q: "How long does an evaluation take?",
    a: "Evaluation time scales with manuscript length. A short story or chapter (under 10,000 words) typically processes in 2–5 minutes. A full novel of 100,000+ words may take 20–40 minutes. You will receive a notification when your evaluation is complete.",
  },
  {
    q: "Can I evaluate the same manuscript multiple times?",
    a: "Yes. Repeated evaluation across revision cycles is one of the core use cases RevisionGrade is designed for. The dashboard tracks your score trend over time so you can measure whether revision is producing real gains.",
  },
  {
    q: "What does a score of 8.0 mean?",
    a: "A score of 8.0 or higher means your manuscript meets the RevisionGrade threshold for agent-facing readiness within our framework. It does not guarantee representation or publication. It means the manuscript has demonstrated craft competency across the 13 evaluation criteria at a level consistent with submittable work.",
  },
  {
    q: "How are scores calculated?",
    a: "Each of the 13 criteria is scored 1–10 by the WAVE framework. A composite readiness score is calculated as a weighted average, with structural criteria (Spine & Causality, Structural Pacing, Character Pressure) weighted more heavily than polish criteria (Dialogue, World Consistency).",
  },
  {
    q: "Does RevisionGrade evaluate genre fiction and literary fiction differently?",
    a: "The 13 criteria apply to all prose narrative. Some criteria — Thematic Coherence, Voice Integrity — weight differently in literary fiction versus commercial genre fiction. Genre calibration is part of the evaluation configuration. If you submit a commercial thriller and a literary novel, the same criteria apply, but genre expectations inform the scoring context.",
  },
];

const REVISE_FAQS = [
  {
    q: "What is a RevisionOpportunity?",
    a: "A RevisionOpportunity is a structured, addressable craft issue produced by the evaluation. Each opportunity includes an original text span, the severity classification (MUST / SHOULD / COULD), a rationale, one to three proposed revisions (A, B, C), and dependency metadata indicating whether resolving this issue affects other parts of the manuscript.",
  },
  {
    q: "Can I choose my own revision instead of A, B, or C?",
    a: "Yes. For every RevisionOpportunity, you may accept a proposed option, keep the original text, reject all proposals, enter a fully custom rewrite, or defer the item for later. Every choice is recorded in your revision session and can be reviewed or changed before you assemble your final revised manuscript.",
  },
  {
    q: "What does 'Blocked' mean in the revision queue?",
    a: "Some MUST items are designated as blocking dependencies. A chapter or passage marked Blocked cannot be committed until an upstream MUST issue is resolved. This prevents you from polishing text that will need to be rewritten again once the structural issue above it is fixed. A blocked item always explains which upstream issue is causing the gate.",
  },
  {
    q: "Can I work chapter by chapter instead of manuscript-wide?",
    a: "Yes. Chapter mode is a first-class workflow in REVISE. In chapter mode, you see only the MUST / SHOULD / COULD opportunities within a selected chapter, with a chapter-specific progress indicator. The canonical queue order is preserved — selecting a chapter simply filters the view, it doesn't change severity or leverage ordering.",
  },
  {
    q: "When is my final revised manuscript produced?",
    a: "Your final revised manuscript is assembled after your revision session, from the saved decision record. The system walks the manuscript in order, applies accepted or custom decisions, preserves original text for kept or rejected items, and produces a clean compiled artifact. You can also export a chapter-by-chapter preview during the session.",
  },
  {
    q: "Will REVISE overwrite my original manuscript?",
    a: "Never. Your original uploaded manuscript is preserved at all times. The revision session builds a separate decision record and compiled preview. The original is always accessible alongside the current compiled state, and every revision decision is auditable.",
  },
];

export default function ResourcesPage() {
  return (
    <div className="bg-rg-ink text-rg-cream min-h-screen font-rg-serif">

      {/* ── HEADER ────────────────────────────────────────────────────────── */}
      <section className="max-w-5xl mx-auto px-6 pt-24 pb-16">
        <p className="font-rg-mono text-xs tracking-[0.22em] uppercase text-rg-gold mb-6">
          Resources
        </p>
        <h1 className="text-5xl sm:text-6xl leading-[1.03] tracking-tight mb-6 max-w-2xl">
          Methodology, guidance, and answers.
        </h1>
        <p className="text-rg-cream2 text-lg leading-relaxed max-w-xl">
          Everything you need to understand how RevisionGrade evaluates manuscripts,
          what the scores mean, and how the REVISE workflow operates.
        </p>
      </section>

      {/* ── QUICK LINKS ───────────────────────────────────────────────────── */}
      <section className="border-t border-rg-cream2/10 bg-rg-ink2">
        <div className="max-w-5xl mx-auto px-6 py-8">
          <div className="flex flex-wrap gap-6">
            {[
              ["Methodology", "#methodology"],
              ["Evaluate — FAQ", "#evaluate-faq"],
              ["Revise — FAQ", "#revise-faq"],
            ].map(([label, href]) => (
              <a
                key={label}
                href={href}
                className="font-rg-mono text-xs tracking-widest uppercase text-rg-cream2 hover:text-rg-gold transition-colors duration-150 border-b border-rg-cream2/20 hover:border-rg-gold pb-1"
              >
                {label}
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* ── METHODOLOGY ───────────────────────────────────────────────────── */}
      <section id="methodology" className="border-t border-rg-cream2/10">
        <div className="max-w-5xl mx-auto px-6 py-20">

          <p className="font-rg-mono text-xs tracking-[0.22em] uppercase text-rg-gold mb-10">
            Methodology
          </p>

          <div className="space-y-12">
            {METHODOLOGY_SECTIONS.map(({ label, body }) => (
              <div key={label} className="grid md:grid-cols-[280px_1fr] gap-8">
                <p className="font-rg-mono text-xs tracking-wide uppercase text-rg-cream border-l-2 border-rg-gold/40 pl-4 self-start pt-0.5">
                  {label}
                </p>
                <p className="text-rg-cream2 text-sm leading-relaxed">
                  {body.trim().replace(/\s+/g, ' ')}
                </p>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* ── EVALUATE FAQ ──────────────────────────────────────────────────── */}
      <section id="evaluate-faq" className="border-t border-rg-cream2/10 bg-rg-ink2">
        <div className="max-w-5xl mx-auto px-6 py-20">

          <p className="font-rg-mono text-xs tracking-[0.22em] uppercase text-rg-gold mb-4">
            Evaluate
          </p>
          <h2 className="text-4xl leading-tight mb-12 max-w-xl">
            Frequently asked questions about evaluation.
          </h2>

          <div className="grid md:grid-cols-2 gap-x-16 gap-y-10">
            {EVALUATE_FAQS.map(({ q, a }) => (
              <div key={q}>
                <p className="text-rg-cream font-rg-mono text-xs tracking-wide uppercase mb-3">{q}</p>
                <p className="text-rg-cream2 text-sm leading-relaxed">{a}</p>
              </div>
            ))}
          </div>

          <div className="mt-12 pt-8 border-t border-rg-cream2/10">
            <Link
              href="/evaluate"
              className="inline-block border border-rg-gold text-rg-gold font-rg-mono text-xs tracking-widest uppercase px-8 py-3 hover:bg-rg-gold hover:text-rg-ink transition-colors duration-200"
            >
              Begin Evaluation
            </Link>
          </div>

        </div>
      </section>

      {/* ── REVISE FAQ ────────────────────────────────────────────────────── */}
      <section id="revise-faq" className="border-t border-rg-cream2/10">
        <div className="max-w-5xl mx-auto px-6 py-20">

          <p className="font-rg-mono text-xs tracking-[0.22em] uppercase text-rg-gold mb-4">
            Revise
          </p>
          <h2 className="text-4xl leading-tight mb-12 max-w-xl">
            Frequently asked questions about the revision workflow.
          </h2>

          <div className="grid md:grid-cols-2 gap-x-16 gap-y-10">
            {REVISE_FAQS.map(({ q, a }) => (
              <div key={q}>
                <p className="text-rg-cream font-rg-mono text-xs tracking-wide uppercase mb-3">{q}</p>
                <p className="text-rg-cream2 text-sm leading-relaxed">{a}</p>
              </div>
            ))}
          </div>

          <div className="mt-12 pt-8 border-t border-rg-cream2/10">
            <Link
              href="/revise"
              className="inline-block border border-rg-cream2/30 text-rg-cream2 font-rg-mono text-xs tracking-widest uppercase px-8 py-3 hover:border-rg-cream2 hover:text-rg-cream transition-colors duration-200"
            >
              Open Revise
            </Link>
          </div>

        </div>
      </section>

      {/* ── DOCTRINE FOOTER ───────────────────────────────────────────────── */}
      <section className="border-t border-rg-cream2/10 bg-rg-ink2">
        <div className="max-w-5xl mx-auto px-6 py-12 text-center">
          <p className="text-rg-dim text-xs font-rg-mono tracking-[0.18em] uppercase">
            Powered by the WAVE Revision System · 13 Story Evaluation Criteria ·
            Framework-driven analysis does not replace human editorial judgment
          </p>
        </div>
      </section>

    </div>
  );
}
