export type WaveCategory =
	| "structure"
	| "voice"
	| "dialogue"
	| "pacing"
	| "clarity"
	| "continuity"
	| "polish"
	| "scene"
	| "character"
	| "narrative"
	| "compression";

export type WaveScope = "sentence" | "paragraph" | "scene" | "chapter";

export interface WaveEntry {
	id: number;
	name: string;
	category: WaveCategory;
	description: string;
	scope: WaveScope;
	dependencies: number[];
	conflicts: number[];
	surgicalAllowed: boolean;
	maxEditRadiusSentences: number;
	priority: number;
	passSource: 1 | 2 | 3;
	criterionIds: string[];
}

export const WAVE_REGISTRY: readonly WaveEntry[] = [
	{
		id: 1,
		name: "Story Spine Integrity",
		category: "structure",
		description: "Verifies central premise, stakes, and directional causality from opening through ending.",
		scope: "chapter",
		dependencies: [],
		conflicts: [8],
		surgicalAllowed: false,
		maxEditRadiusSentences: 80,
		priority: 100,
		passSource: 1,
		criterionIds: ["STRUCTURE_SPINE", "CORE_CONFLICT"],
	},
	{
		id: 2,
		name: "Act Turn Placement",
		category: "structure",
		description: "Aligns first-turn, midpoint, and final-turn beats to maintain forward narrative pressure.",
		scope: "chapter",
		dependencies: [1],
		conflicts: [8],
		surgicalAllowed: false,
		maxEditRadiusSentences: 80,
		priority: 99,
		passSource: 1,
		criterionIds: ["ACT_STRUCTURE", "TURNING_POINTS"],
	},
	{
		id: 3,
		name: "Inciting Incident Pressure",
		category: "narrative",
		description: "Strengthens the trigger event so protagonist action becomes inevitable rather than optional.",
		scope: "scene",
		dependencies: [1],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 24,
		priority: 98,
		passSource: 1,
		criterionIds: ["INCITING_INCIDENT", "NARRATIVE_MOMENTUM"],
	},
	{
		id: 4,
		name: "Midpoint Reversal Calibration",
		category: "structure",
		description: "Ensures midpoint shifts objective reality and re-frames risk for the remainder of the story.",
		scope: "chapter",
		dependencies: [2, 3],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 60,
		priority: 97,
		passSource: 1,
		criterionIds: ["MIDPOINT_REVERSAL", "STAKES_ESCALATION"],
	},
	{
		id: 5,
		name: "Climax Causality Ladder",
		category: "structure",
		description: "Validates that climax outcomes are earned by preceding decisions, failures, and constraints.",
		scope: "chapter",
		dependencies: [2, 4],
		conflicts: [8],
		surgicalAllowed: false,
		maxEditRadiusSentences: 80,
		priority: 96,
		passSource: 1,
		criterionIds: ["CLIMAX_CAUSALITY", "PAYOFF_EARNED"],
	},
	{
		id: 6,
		name: "Ending Resolution Payoff",
		category: "narrative",
		description: "Confirms final movement resolves primary promise while preserving thematic residue.",
		scope: "chapter",
		dependencies: [5],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 80,
		priority: 95,
		passSource: 1,
		criterionIds: ["ENDING_PAYOFF", "PROMISE_FULFILLMENT"],
	},
	{
		id: 7,
		name: "POV Architecture Audit",
		category: "narrative",
		description: "Checks point-of-view allocation, handoff logic, and narrative authority consistency.",
		scope: "chapter",
		dependencies: [1],
		conflicts: [12],
		surgicalAllowed: false,
		maxEditRadiusSentences: 60,
		priority: 94,
		passSource: 1,
		criterionIds: ["POV_ARCHITECTURE", "NARRATIVE_AUTHORITY"],
	},
	{
		id: 8,
		name: "Experimental Form Weave",
		category: "narrative",
		description: "Integrates non-linear or formal experimentation without breaking reader orientation.",
		scope: "chapter",
		dependencies: [1],
		conflicts: [1, 2, 5, 40],
		surgicalAllowed: false,
		maxEditRadiusSentences: 80,
		priority: 88,
		passSource: 1,
		criterionIds: ["FORM_EXPERIMENTATION", "READABILITY_GUARDRAIL"],
	},
	{
		id: 9,
		name: "Theme Thread Density",
		category: "narrative",
		description: "Balances thematic recurrence so motifs accumulate without overt signaling.",
		scope: "chapter",
		dependencies: [1, 3],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 60,
		priority: 93,
		passSource: 1,
		criterionIds: ["THEMATIC_COHESION", "MOTIF_DISTRIBUTION"],
	},
	{
		id: 10,
		name: "Narrative Promise Fulfillment",
		category: "structure",
		description: "Cross-checks opening hooks against ending delivery for trust-preserving closure.",
		scope: "chapter",
		dependencies: [1, 6, 9],
		conflicts: [8],
		surgicalAllowed: false,
		maxEditRadiusSentences: 80,
		priority: 92,
		passSource: 1,
		criterionIds: ["READER_PROMISE", "ARC_COMPLETENESS"],
	},
	{
		id: 11,
		name: "Narrative Voice Consistency",
		category: "voice",
		description: "Stabilizes narrator texture, stance, and lexical bias across the manuscript.",
		scope: "chapter",
		dependencies: [7, 10],
		conflicts: [14],
		surgicalAllowed: true,
		maxEditRadiusSentences: 18,
		priority: 91,
		passSource: 1,
		criterionIds: ["VOICE_CONSISTENCY", "NARRATOR_STANCE"],
	},
	{
		id: 12,
		name: "POV Voice Distinction",
		category: "voice",
		description: "Differentiates focal voices so each perspective remains instantly recognizable.",
		scope: "scene",
		dependencies: [7, 11],
		conflicts: [7, 18],
		surgicalAllowed: true,
		maxEditRadiusSentences: 12,
		priority: 90,
		passSource: 1,
		criterionIds: ["POV_VOICE_DISTINCTION", "FOCALIZATION"],
	},
	{
		id: 13,
		name: "Diction Register Alignment",
		category: "voice",
		description: "Aligns word choice register with genre, era, and character social positioning.",
		scope: "paragraph",
		dependencies: [11],
		conflicts: [52],
		surgicalAllowed: true,
		maxEditRadiusSentences: 8,
		priority: 89,
		passSource: 1,
		criterionIds: ["DICTION_REGISTER", "LEXICAL_COHERENCE"],
	},
	{
		id: 14,
		name: "Emotional Tone Modulation",
		category: "voice",
		description: "Shapes tonal gradients so emotional intensity rises and releases deliberately.",
		scope: "scene",
		dependencies: [11, 13],
		conflicts: [11, 55],
		surgicalAllowed: true,
		maxEditRadiusSentences: 12,
		priority: 88,
		passSource: 1,
		criterionIds: ["TONE_CONTROL", "EMOTIONAL_ARC"],
	},
	{
		id: 15,
		name: "Character Motivation Clarity",
		category: "character",
		description: "Makes immediate character objectives legible at decision points and reversals.",
		scope: "scene",
		dependencies: [1, 3],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 20,
		priority: 92,
		passSource: 1,
		criterionIds: ["MOTIVATION_CLARITY", "CHARACTER_OBJECTIVE"],
	},
	{
		id: 16,
		name: "Desire-Obstacle Escalation",
		category: "character",
		description: "Escalates friction between want and resistance to sustain dramatic propulsion.",
		scope: "scene",
		dependencies: [15],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 20,
		priority: 90,
		passSource: 1,
		criterionIds: ["DESIRE_OBSTACLE", "DRAMATIC_PRESSURE"],
	},
	{
		id: 17,
		name: "Character Arc Inflection Points",
		category: "character",
		description: "Places attitude and behavior shifts at earned moments rather than convenience beats.",
		scope: "chapter",
		dependencies: [4, 15, 16],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 30,
		priority: 89,
		passSource: 1,
		criterionIds: ["ARC_INFLECTION", "CHARACTER_GROWTH"],
	},
	{
		id: 18,
		name: "Interior Monologue Precision",
		category: "voice",
		description: "Refines internal thought prose for specificity, cadence, and viewpoint containment.",
		scope: "paragraph",
		dependencies: [12, 14, 15],
		conflicts: [12, 53],
		surgicalAllowed: true,
		maxEditRadiusSentences: 6,
		priority: 86,
		passSource: 1,
		criterionIds: ["INTERIORITY_PRECISION", "POV_CONTAINMENT"],
	},
	{
		id: 19,
		name: "Character Idiolect Signatures",
		category: "character",
		description: "Builds distinct lexical and syntactic fingerprints for principal speakers.",
		scope: "scene",
		dependencies: [12, 13, 15],
		conflicts: [54],
		surgicalAllowed: true,
		maxEditRadiusSentences: 10,
		priority: 85,
		passSource: 1,
		criterionIds: ["IDIOLECT_SIGNATURE", "CHARACTER_DIFFERENTIATION"],
	},
	{
		id: 20,
		name: "Backstory Load Balancing",
		category: "character",
		description: "Distributes history reveals to maximize relevance and minimize exposition drag.",
		scope: "chapter",
		dependencies: [15, 17],
		conflicts: [35],
		surgicalAllowed: false,
		maxEditRadiusSentences: 24,
		priority: 84,
		passSource: 1,
		criterionIds: ["BACKSTORY_DOSING", "EXPOSITION_BALANCE"],
	},
	{
		id: 21,
		name: "Dialogue Goal Per Line",
		category: "dialogue",
		description: "Ensures each spoken line performs intent: pressure, concealment, reveal, or pivot.",
		scope: "paragraph",
		dependencies: [15, 19],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 6,
		priority: 88,
		passSource: 1,
		criterionIds: ["DIALOGUE_FUNCTION", "INTENT_DENSITY"],
	},
	{
		id: 22,
		name: "Subtext Signal Strength",
		category: "dialogue",
		description: "Increases implied meaning beneath explicit speech without sacrificing comprehension.",
		scope: "paragraph",
		dependencies: [21, 14],
		conflicts: [37],
		surgicalAllowed: true,
		maxEditRadiusSentences: 6,
		priority: 87,
		passSource: 2,
		criterionIds: ["SUBTEXT_DEPTH", "IMPLICIT_CONFLICT"],
	},
	{
		id: 23,
		name: "Attribution Friction Reduction",
		category: "dialogue",
		description: "Optimizes tags, beats, and speaker cues for effortless conversation tracking.",
		scope: "paragraph",
		dependencies: [21],
		conflicts: [57],
		surgicalAllowed: true,
		maxEditRadiusSentences: 5,
		priority: 86,
		passSource: 2,
		criterionIds: ["ATTRIBUTION_CLARITY", "DIALOGUE_FLOW"],
	},
	{
		id: 24,
		name: "Dialogue Beat Integration",
		category: "dialogue",
		description: "Integrates action beats with speech to anchor body language and blocking.",
		scope: "paragraph",
		dependencies: [21, 23],
		conflicts: [33],
		surgicalAllowed: true,
		maxEditRadiusSentences: 6,
		priority: 85,
		passSource: 2,
		criterionIds: ["DIALOGUE_BEATS", "EMBODIED_SPEECH"],
	},
	{
		id: 25,
		name: "Interruptions and Overlap Naturalism",
		category: "dialogue",
		description: "Tunes interruptions and cutoffs to sound organic while preserving readability.",
		scope: "paragraph",
		dependencies: [22, 24],
		conflicts: [56],
		surgicalAllowed: true,
		maxEditRadiusSentences: 5,
		priority: 84,
		passSource: 2,
		criterionIds: ["SPEECH_OVERLAP", "CONVERSATION_REALISM"],
	},
	{
		id: 26,
		name: "Exposition in Dialogue Deflation",
		category: "dialogue",
		description: "Removes implausible explainy lines and migrates context to dramatic action.",
		scope: "scene",
		dependencies: [20, 22],
		conflicts: [31],
		surgicalAllowed: false,
		maxEditRadiusSentences: 12,
		priority: 83,
		passSource: 2,
		criterionIds: ["EXPOSITION_DEFLATION", "DIALOGUE_AUTHENTICITY"],
	},
	{
		id: 27,
		name: "Conflict Escalation Through Speech",
		category: "dialogue",
		description: "Shapes verbal exchanges to increase stakes and force consequential choices.",
		scope: "scene",
		dependencies: [16, 21, 22],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 14,
		priority: 82,
		passSource: 2,
		criterionIds: ["VERBAL_CONFLICT", "STAKES_IN_DIALOGUE"],
	},
	{
		id: 28,
		name: "Distinct Speaker Rhythm",
		category: "dialogue",
		description: "Differentiates cadence and sentence length patterns among core speakers.",
		scope: "paragraph",
		dependencies: [19, 21],
		conflicts: [55],
		surgicalAllowed: true,
		maxEditRadiusSentences: 5,
		priority: 81,
		passSource: 2,
		criterionIds: ["SPEAKER_RHYTHM", "VOICE_DIFFERENTIATION"],
	},
	{
		id: 29,
		name: "Silence and Omission Placement",
		category: "dialogue",
		description: "Places intentional gaps, pauses, and withheld responses for dramatic leverage.",
		scope: "scene",
		dependencies: [22, 27],
		conflicts: [37],
		surgicalAllowed: true,
		maxEditRadiusSentences: 8,
		priority: 80,
		passSource: 2,
		criterionIds: ["SILENCE_STRATEGY", "OMISSION_DRAMA"],
	},
	{
		id: 30,
		name: "Scene Exit Dialogue Hooks",
		category: "dialogue",
		description: "Engineers scene-closing lines that propel curiosity into the next beat.",
		scope: "scene",
		dependencies: [21, 27, 29],
		conflicts: [44],
		surgicalAllowed: true,
		maxEditRadiusSentences: 10,
		priority: 79,
		passSource: 2,
		criterionIds: ["EXIT_HOOKS", "SCENE_HANDOFF"],
	},
	{
		id: 31,
		name: "Macro Pacing Gradient",
		category: "pacing",
		description: "Balances acceleration and deceleration across acts to avoid narrative flatlining.",
		scope: "chapter",
		dependencies: [1, 2, 3],
		conflicts: [26],
		surgicalAllowed: false,
		maxEditRadiusSentences: 40,
		priority: 86,
		passSource: 2,
		criterionIds: ["MACRO_PACING", "MOMENTUM_CURVE"],
	},
	{
		id: 32,
		name: "Tension Curve Continuity",
		category: "pacing",
		description: "Maintains pressure continuity so tension dips are intentional and earned.",
		scope: "chapter",
		dependencies: [16, 27, 31],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 30,
		priority: 85,
		passSource: 2,
		criterionIds: ["TENSION_CURVE", "PRESSURE_CONTINUITY"],
	},
	{
		id: 33,
		name: "Paragraph Momentum Control",
		category: "pacing",
		description: "Adjusts paragraph length and syntactic drag to sustain forward reader motion.",
		scope: "paragraph",
		dependencies: [31],
		conflicts: [24],
		surgicalAllowed: true,
		maxEditRadiusSentences: 6,
		priority: 84,
		passSource: 2,
		criterionIds: ["PARAGRAPH_MOMENTUM", "READING_VELOCITY"],
	},
	{
		id: 34,
		name: "Sentence Energy Variation",
		category: "pacing",
		description: "Varies syntax and stress patterns to avoid monotone sentence cadence.",
		scope: "sentence",
		dependencies: [33],
		conflicts: [52],
		surgicalAllowed: true,
		maxEditRadiusSentences: 3,
		priority: 83,
		passSource: 2,
		criterionIds: ["SENTENCE_ENERGY", "CADENCE_VARIATION"],
	},
	{
		id: 35,
		name: "Drag Segment Compression",
		category: "pacing",
		description: "Compresses low-yield passages while preserving emotional and plot utility.",
		scope: "scene",
		dependencies: [31, 33],
		conflicts: [20],
		surgicalAllowed: false,
		maxEditRadiusSentences: 18,
		priority: 82,
		passSource: 2,
		criterionIds: ["DRAG_COMPRESSION", "SCENE_EFFICIENCY"],
	},
	{
		id: 36,
		name: "Clarity of Causal Links",
		category: "clarity",
		description: "Makes cause-effect relationships explicit where ambiguity harms comprehension.",
		scope: "scene",
		dependencies: [1, 5, 31],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 10,
		priority: 85,
		passSource: 2,
		criterionIds: ["CAUSAL_CLARITY", "LOGICAL_FLOW"],
	},
	{
		id: 37,
		name: "Pronoun and Referent Clarity",
		category: "clarity",
		description: "Eliminates ambiguous references that force rereads or misattribution.",
		scope: "sentence",
		dependencies: [34, 36],
		conflicts: [22, 29],
		surgicalAllowed: true,
		maxEditRadiusSentences: 2,
		priority: 84,
		passSource: 2,
		criterionIds: ["REFERENT_CLARITY", "PRONOUN_RESOLUTION"],
	},
	{
		id: 38,
		name: "Temporal Marker Precision",
		category: "clarity",
		description: "Clarifies when events occur relative to prior and upcoming scene anchors.",
		scope: "paragraph",
		dependencies: [36],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 5,
		priority: 83,
		passSource: 2,
		criterionIds: ["TEMPORAL_PRECISION", "TIMELINE_READABILITY"],
	},
	{
		id: 39,
		name: "Spatial Orientation Clarity",
		category: "clarity",
		description: "Improves reader spatial mapping during movement, action, and blocking shifts.",
		scope: "scene",
		dependencies: [36, 38],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 10,
		priority: 82,
		passSource: 2,
		criterionIds: ["SPATIAL_CLARITY", "BLOCKING_ORIENTATION"],
	},
	{
		id: 40,
		name: "Cognitive Load Reduction",
		category: "clarity",
		description: "Reduces stacked abstractions so complex ideas remain processable on first pass.",
		scope: "paragraph",
		dependencies: [36, 37, 39],
		conflicts: [8],
		surgicalAllowed: true,
		maxEditRadiusSentences: 6,
		priority: 81,
		passSource: 2,
		criterionIds: ["COGNITIVE_LOAD", "READER_PROCESSING"],
	},
	{
		id: 41,
		name: "Scene Objective Sharpness",
		category: "scene",
		description: "Defines scene-level objective, opposition, and consequence with minimal drift.",
		scope: "scene",
		dependencies: [1, 15, 31],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 18,
		priority: 88,
		passSource: 2,
		criterionIds: ["SCENE_OBJECTIVE", "MICRO_DRAMA"],
	},
	{
		id: 42,
		name: "Scene Transition Coherence",
		category: "continuity",
		description: "Tightens scene-to-scene handoffs for time, place, and emotional momentum.",
		scope: "scene",
		dependencies: [41, 31],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 18,
		priority: 87,
		passSource: 2,
		criterionIds: ["SCENE_TRANSITIONS", "FLOW_CONTINUITY"],
	},
	{
		id: 43,
		name: "Scene Entry Timing",
		category: "scene",
		description: "Moves scene entry points later to start near consequential motion.",
		scope: "scene",
		dependencies: [31, 41, 42],
		conflicts: [20],
		surgicalAllowed: false,
		maxEditRadiusSentences: 16,
		priority: 80,
		passSource: 3,
		criterionIds: ["LATE_ENTRY", "SCENE_EFFICIENCY"],
	},
	{
		id: 44,
		name: "Scene Exit Resonance",
		category: "scene",
		description: "Shapes scene endings to leave unresolved energy and thematic echo.",
		scope: "scene",
		dependencies: [30, 41, 43],
		conflicts: [30],
		surgicalAllowed: true,
		maxEditRadiusSentences: 10,
		priority: 79,
		passSource: 3,
		criterionIds: ["SCENE_EXIT", "RESONANT_HANDOFF"],
	},
	{
		id: 45,
		name: "Continuity Prop Tracking",
		category: "continuity",
		description: "Tracks physical objects and state changes to prevent impossible appearances.",
		scope: "chapter",
		dependencies: [42, 39],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 10,
		priority: 78,
		passSource: 3,
		criterionIds: ["PROP_CONTINUITY", "STATE_TRACKING"],
	},
	{
		id: 46,
		name: "Timeline Consistency",
		category: "continuity",
		description: "Validates chronology math for elapsed time, sequencing, and travel feasibility.",
		scope: "chapter",
		dependencies: [38, 42, 45],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 14,
		priority: 77,
		passSource: 3,
		criterionIds: ["TIMELINE_CONSISTENCY", "CHRONOLOGY_INTEGRITY"],
	},
	{
		id: 47,
		name: "Character Presence Continuity",
		category: "continuity",
		description: "Ensures who is present, absent, or aware remains coherent across scenes.",
		scope: "scene",
		dependencies: [45, 15],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 10,
		priority: 76,
		passSource: 3,
		criterionIds: ["PRESENCE_CONTINUITY", "CHARACTER_LOGISTICS"],
	},
	{
		id: 48,
		name: "Emotional Continuity Between Scenes",
		category: "continuity",
		description: "Carries emotional state forward so reactions match prior scene intensity.",
		scope: "scene",
		dependencies: [17, 42, 46],
		conflicts: [14],
		surgicalAllowed: true,
		maxEditRadiusSentences: 12,
		priority: 75,
		passSource: 3,
		criterionIds: ["EMOTIONAL_CONTINUITY", "AFFECTIVE_LOGIC"],
	},
	{
		id: 49,
		name: "Setting Continuity Texture",
		category: "continuity",
		description: "Maintains stable environment details while allowing deliberate atmospheric shifts.",
		scope: "scene",
		dependencies: [39, 45],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 10,
		priority: 74,
		passSource: 3,
		criterionIds: ["SETTING_CONTINUITY", "ENVIRONMENTAL_STABILITY"],
	},
	{
		id: 50,
		name: "Cross-Scene Callback Integrity",
		category: "scene",
		description: "Confirms callbacks and echoes resolve as intended across distant scenes.",
		scope: "chapter",
		dependencies: [9, 44, 48],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 16,
		priority: 73,
		passSource: 3,
		criterionIds: ["CALLBACK_INTEGRITY", "LONG_RANGE_COHESION"],
	},
	{
		id: 51,
		name: "Line Edit Concision",
		category: "polish",
		description: "Cuts surplus wording while retaining voice, intent, and dramatic precision.",
		scope: "sentence",
		dependencies: [35, 40],
		conflicts: [19],
		surgicalAllowed: true,
		maxEditRadiusSentences: 2,
		priority: 82,
		passSource: 3,
		criterionIds: ["CONCISION", "LINE_EFFICIENCY"],
	},
	{
		id: 52,
		name: "Verb Strength Upgrade",
		category: "polish",
		description: "Replaces weak verb constructions with precise, active alternatives.",
		scope: "sentence",
		dependencies: [34, 51],
		conflicts: [13, 34],
		surgicalAllowed: true,
		maxEditRadiusSentences: 2,
		priority: 81,
		passSource: 3,
		criterionIds: ["VERB_STRENGTH", "ACTION_CLARITY"],
	},
	{
		id: 53,
		name: "Adverb and Filter Word Trim",
		category: "polish",
		description: "Reduces habitual modifiers and filter phrases that dilute immediacy.",
		scope: "sentence",
		dependencies: [51],
		conflicts: [18],
		surgicalAllowed: true,
		maxEditRadiusSentences: 2,
		priority: 80,
		passSource: 3,
		criterionIds: ["FILTER_WORD_TRIM", "MODIFIER_DISCIPLINE"],
	},
	{
		id: 54,
		name: "Repetition and Echo Cleanup",
		category: "polish",
		description: "Removes accidental repeated wording while preserving intentional motif returns.",
		scope: "paragraph",
		dependencies: [51, 53],
		conflicts: [19],
		surgicalAllowed: true,
		maxEditRadiusSentences: 4,
		priority: 79,
		passSource: 3,
		criterionIds: ["REPETITION_CLEANUP", "LEXICAL_VARIETY"],
	},
	{
		id: 55,
		name: "Rhythm and Cadence Polish",
		category: "polish",
		description: "Refines sentence music, stress flow, and breath rhythm for high readability.",
		scope: "paragraph",
		dependencies: [52, 54],
		conflicts: [14, 28],
		surgicalAllowed: true,
		maxEditRadiusSentences: 4,
		priority: 78,
		passSource: 3,
		criterionIds: ["CADENCE_POLISH", "PROSE_MUSICALITY"],
	},
	{
		id: 56,
		name: "Grammar and Syntax Correctness",
		category: "polish",
		description: "Corrects grammatical and structural errors while protecting intentional style.",
		scope: "sentence",
		dependencies: [51],
		conflicts: [25],
		surgicalAllowed: true,
		maxEditRadiusSentences: 2,
		priority: 77,
		passSource: 3,
		criterionIds: ["GRAMMAR_CORRECTNESS", "SYNTAX_CONTROL"],
	},
	{
		id: 57,
		name: "Punctuation Intent Calibration",
		category: "polish",
		description: "Tunes punctuation for clarity, emphasis, and voice-consistent pacing.",
		scope: "sentence",
		dependencies: [56, 55],
		conflicts: [23],
		surgicalAllowed: true,
		maxEditRadiusSentences: 2,
		priority: 76,
		passSource: 3,
		criterionIds: ["PUNCTUATION_INTENT", "MICRO_PACING"],
	},
	{
		id: 58,
		name: "Formatting and Readability Sweep",
		category: "polish",
		description: "Normalizes paragraphing and presentation signals for frictionless reading.",
		scope: "chapter",
		dependencies: [56],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 6,
		priority: 75,
		passSource: 3,
		criterionIds: ["FORMAT_READABILITY", "PRESENTATION_HYGIENE"],
	},
	{
		id: 59,
		name: "Final Consistency Sweep",
		category: "continuity",
		description: "Performs last integrated continuity check across timeline, props, voice, and facts.",
		scope: "chapter",
		dependencies: [46, 47, 49, 58],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 10,
		priority: 74,
		passSource: 3,
		criterionIds: ["FINAL_CONSISTENCY", "CANON_STABILITY"],
	},
	{
		id: 60,
		name: "Title and Chapter Hook Alignment",
		category: "narrative",
		description: "Aligns macro framing signals with delivered thematic and plot trajectories.",
		scope: "chapter",
		dependencies: [10, 44, 59],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 12,
		priority: 73,
		passSource: 3,
		criterionIds: ["HOOK_ALIGNMENT", "FRAMING_COHERENCE"],
	},
	{
		id: 61,
		name: "Sensory Specificity Final Pass",
		category: "clarity",
		description: "Adds precise sensory anchors where abstraction weakens scene immediacy.",
		scope: "paragraph",
		dependencies: [39, 55, 59],
		conflicts: [35],
		surgicalAllowed: true,
		maxEditRadiusSentences: 4,
		priority: 72,
		passSource: 3,
		criterionIds: ["SENSORY_SPECIFICITY", "IMMERSION_FINAL"],
	},
	{
		id: 62,
		name: "Copyedit Exception Audit",
		category: "polish",
		description: "Verifies intentional rule breaks are preserved and unintentional ones corrected.",
		scope: "chapter",
		dependencies: [56, 57, 59],
		conflicts: [],
		surgicalAllowed: true,
		maxEditRadiusSentences: 6,
		priority: 71,
		passSource: 3,
		criterionIds: ["COPYEDIT_AUDIT", "STYLE_EXCEPTION_CONTROL"],
	},
	{
		id: 63,
		name: "Final Read-Aloud Integrity",
		category: "polish",
		description: "Performs end-to-end oral-flow validation for rhythm, clarity, and emotional truth.",
		scope: "chapter",
		dependencies: [55, 57, 60, 62],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 16,
		priority: 70,
		passSource: 3,
		criterionIds: ["READ_ALOUD_INTEGRITY", "FINAL_QA"],
	},
	{
		id: 64,
		name: "Prose Compression",
		category: "compression",
		description: "Removes filler adverbs and hedge phrases from moderate-density literary prose without altering narrative texture.",
		scope: "sentence",
		dependencies: [],
		conflicts: [],
		surgicalAllowed: false,
		maxEditRadiusSentences: 1,
		priority: 85,
		passSource: 2,
		criterionIds: ["FILLER_REDUCTION", "PROSE_DENSITY"],
	},
];

const WAVE_BY_ID = new Map<number, WaveEntry>(
	WAVE_REGISTRY.map((wave) => [wave.id, wave]),
);

export function getWave(id: number): WaveEntry | undefined {
	return WAVE_BY_ID.get(id);
}

export function getWavesByCategory(cat: WaveCategory): readonly WaveEntry[] {
	return WAVE_REGISTRY.filter((wave) => wave.category === cat);
}

export function getWavesByPass(pass: 1 | 2 | 3): readonly WaveEntry[] {
	return WAVE_REGISTRY.filter((wave) => wave.passSource === pass);
}

export function getConflictingWaves(id: number): readonly WaveEntry[] {
	const wave = getWave(id);
	if (!wave) {
		return [];
	}

	const conflictIds = new Set<number>(wave.conflicts);
	for (const candidate of WAVE_REGISTRY) {
		if (candidate.id !== id && candidate.conflicts.includes(id)) {
			conflictIds.add(candidate.id);
		}
	}

	return [...conflictIds]
		.map((conflictId) => WAVE_BY_ID.get(conflictId))
		.filter((entry): entry is WaveEntry => entry !== undefined)
		.sort((a, b) => a.id - b.id);
}

export function getDependenciesOf(id: number): readonly WaveEntry[] {
	const wave = getWave(id);
	if (!wave) {
		return [];
	}

	return wave.dependencies
		.map((dependencyId) => WAVE_BY_ID.get(dependencyId))
		.filter((entry): entry is WaveEntry => entry !== undefined)
		.sort((a, b) => a.id - b.id);
}
