import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Shield, Heart, AlertCircle, CheckCircle2, BookOpen, Download, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';

export default function EthicsAndSafety() {
  const handleDownloadChecklist = () => {
    const checklistText = `INCLUSIVITY REVIEW CHECKLIST
Questions to ask when reviewing Base44's inclusivity notes

1. INTENT AND NECESSITY
□ Does this line/description clearly serve a story purpose (characterization, conflict, theme), or is it just habit or cheap shorthand?
□ If a stranger read this sentence with no context, what would they reasonably think it says about the group mentioned?
□ Could the same effect be achieved without leaning on identity (race, gender, disability, etc.) at all?

2. POINT OF VIEW AND OWNERSHIP
□ Whose voice is this: the character's, or the narrator's?
□ If it is the narrator, does this language reflect your view, or is it accidentally echoing a biased character?
□ Is this identity being written from the inside (lived experience / deep research) or the outside? If outside, have you been specific and respectful enough?

3. PATTERNS, NOT ONE-OFFS
□ Looking across the chapter or book, does this group mostly appear in one role (victim, villain, comic relief, helper, love interest)?
□ Are certain adjectives or labels only ever applied to one group (e.g., "sassy", "exotic", "crazy", "illegal")?
□ If you swapped the group for another, would the pattern suddenly look obviously biased or clichéd?

4. LANGUAGE CHOICES AND LABELS
□ Am I using any terms that current inclusive-language guides flag as outdated, dehumanizing, or stigmatizing? (e.g., "the disabled", "illegals", "crazy people")
□ Is identity mentioned only when it's relevant, or am I calling out race, gender, or disability where I wouldn't for a default/dominant group?
□ Can I swap a label for a more precise or person-first phrasing without losing power? (e.g., "disabled people" or "people with X" vs "the X")

5. IMPACT ON REAL READERS
□ If a reader who shares this identity saw only this representation, how might it land: seen, stereotyped, erased, or used as a prop?
□ Does this joke/description punch down at people with less power, or punch up at systems and structures?
□ If someone flagged this line in a review or sensitivity read, could you clearly explain why you chose it and what you were trying to do?

6. REVISION DECISIONS
For each flagged instance, note:
□ Am I keeping this as-is because it's essential to character or theme?
□ Am I tweaking wording or context to reduce collateral harm while keeping the same dramatic function?
□ Am I replacing or cutting because it's lazy shorthand, cliché, or not worth the cost?

If you consistently answer "I'm not sure": Mark those spots for discussion with a trusted beta reader, editor, or sensitivity reader who shares (or deeply knows) the identity in question.

---
Generated by RevisionGrade™ - base44.com`;

    const blob = new Blob([checklistText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'inclusivity-review-checklist.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50">
      <div className="max-w-4xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="mb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-100 text-indigo-700 text-sm font-medium mb-4">
            <Shield className="w-4 h-4" />
            Ethics & Safety
          </div>
          <h1 className="text-4xl font-bold text-slate-900 mb-3">
            How Base44 Handles Sensitive Language
          </h1>
          <p className="text-lg text-slate-600">
            Supporting creative freedom while making bias and risk visible
          </p>
        </div>

        {/* Intro Statement */}
        <Card className="mb-8 border-l-4 border-l-indigo-500">
          <CardContent className="p-6">
            <p className="text-slate-700 text-lg">
              Base44 is built to help you tell the story you want to tell while reducing avoidable risk around slurs, 
              hate speech, and harmful stereotypes. <strong>It never "censors" your work in secret, and it never tries 
              to make your characters less complex.</strong>
            </p>
            <p className="text-slate-600 text-sm mt-3">
              <strong>What this is not:</strong> a content filter, a moral judge, or a replacement for your creative judgment.
            </p>
          </CardContent>
        </Card>

        {/* What Counts as Sensitive Language */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertCircle className="w-5 h-5 text-amber-600" />
              What Base44 treats as sensitive language
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-slate-600 text-sm mb-4">
              Base44 pays closer attention when your writing includes:
            </p>

            <div className="space-y-3">
              <div>
                <h3 className="font-semibold text-slate-900 mb-1">Explicit slurs</h3>
                <p className="text-slate-600 text-sm">
                  Words that have been widely used as insults against a group based on race, ethnicity, religion, 
                  sexuality, gender, disability, or nationality.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-slate-900 mb-1">Reclaimed labels and community terms</h3>
                <p className="text-slate-600 text-sm">
                  Words like "queer" or "dyke" that started as slurs but are now used positively in many LGBTQ+ communities, 
                  especially as self-descriptions.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-slate-900 mb-1">Group-directed insults and generalizations</h3>
                <p className="text-slate-600 text-sm">
                  Phrases that attack whole groups ("[group] are trash", "they're animals", "they don't belong here"), 
                  even if they don't use a classic slur.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-slate-900 mb-1">Dehumanizing or violent language</h3>
                <p className="text-slate-600 text-sm">
                  References to groups as pests, animals, or enemies to be "rounded up", "driven out", or harmed.
                </p>
              </div>
            </div>

            <div className="mt-4 p-4 rounded-lg bg-slate-50 border border-slate-200">
              <p className="text-sm text-slate-700">
                <strong>You can still write all of these if they serve your story.</strong> Base44's job is to highlight 
                where they appear and how they function, so you can decide what to keep, revise, or foreground for agents 
                and publishers.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* What Base44 Does */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-green-600" />
              What Base44 does with sensitive language
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-slate-600 text-sm mb-4">
              Base44 does not judge your work — it maps risk, intent, and interpretation so you can make informed 
              creative choices.
            </p>

            <div className="space-y-4">
              <div className="border-l-4 border-l-red-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">
                  High-risk cases (e.g., explicit slurs, calls for violence)
                </h3>
                <ul className="list-disc list-inside text-slate-600 text-sm space-y-1">
                  <li>Clearly marked as market / platform risk</li>
                  <li>Base44 will not automatically rewrite them or suggest a "spicier" insult</li>
                  <li>You'll see an explanation of why the line is risky, so you can decide whether to keep it 
                      for character realism or adjust it</li>
                </ul>
              </div>

              <div className="border-l-4 border-l-green-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">
                  Reclaimed or community uses (e.g., "I'm queer", "dykes on bikes")
                </h3>
                <ul className="list-disc list-inside text-slate-600 text-sm space-y-1">
                  <li>Treated as valid in-group or neutral usage</li>
                  <li>Base44 leaves this language in place but still marks it as sensitive, so you and your editor 
                      know it may be read differently by different audiences</li>
                </ul>
              </div>

              <div className="border-l-4 border-l-amber-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">Historical or analytical mentions</h3>
                <ul className="list-disc list-inside text-slate-600 text-sm space-y-1">
                  <li>When you discuss a slur as a topic ("this word has been used as a weapon"), Base44 recognizes 
                      that you are explaining, not endorsing</li>
                  <li>It preserves the passage and may suggest adding a short content note if usage is frequent 
                      or intense</li>
                </ul>
              </div>

              <div className="border-l-4 border-l-blue-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">
                  Implied harm without repeating the word
                </h3>
                <ul className="list-disc list-inside text-slate-600 text-sm space-y-1">
                  <li>Lines like "the word you don't repeat" or "the insult hit harder than the punch" are usually 
                      allowed to pass through unchanged</li>
                  <li>Base44 understands these as showing harm without re-using the term, which is often a strong 
                      craft choice</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* What Base44 Will Never Do */}
        <Card className="mb-8 border-2 border-red-200 bg-red-50/50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-red-900">
              <Shield className="w-5 h-5" />
              What Base44 will never do
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-red-800 mb-3">
              To keep you and your readers safer, Base44 is deliberately limited in a few key ways:
            </p>
            <ul className="list-disc list-inside text-sm text-red-900 space-y-2">
              <li><strong>It will not invent slurs or hate speech</strong></li>
              <li><strong>It will not suggest replacing one slur with another,</strong> or with a "nicer" phrase that 
                  still carries the same hateful idea</li>
              <li><strong>It will not recommend slurs—reclaimed or not—to neutral narrators or to characters outside 
                  the communities that use them</strong></li>
            </ul>
            <div className="mt-4 pt-4 border-t border-red-200">
              <p className="text-sm text-red-800">
                If Base44 is unsure, it prefers to flag and explain rather than quietly change your words.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Why This Matters */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Heart className="w-5 h-5 text-indigo-600" />
              Why this matters for you
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h3 className="font-semibold text-slate-900 mb-2">Creative control stays with you</h3>
              <p className="text-slate-600 text-sm">
                Base44 shows you where language might trigger retailer policies, content warnings, or reader pushback, 
                but every actual change is your choice.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-slate-900 mb-2">You can write complex, flawed characters</h3>
              <p className="text-slate-600 text-sm">
                Bigoted characters, oppressive systems, and harsh realities belong in fiction and nonfiction. Base44's 
                role is to separate character voice from authorial stance, and to make the potential risks visible.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-slate-900 mb-2">You get clearer conversations with agents and publishers</h3>
              <p className="text-slate-600 text-sm">
                When sensitive language is labeled and explained, you can talk about it in terms of intention, market 
                positioning, and alternative options instead of reacting to last-minute surprises.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Inclusivity and Bias Section */}
        <Card className="mb-8 border-l-4 border-l-purple-500">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-purple-600" />
              Checking inclusivity and bias in your narrative voice
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-slate-600 text-sm">
              Base44 is not here to flatten your characters. It is here to help you notice patterns in your narrative 
              voice that might send messages you never intended.
            </p>

            <div>
              <h3 className="font-semibold text-slate-900 mb-2">What "narrative voice" means here</h3>
              <p className="text-slate-600 text-sm mb-2">By "narrative voice," Base44 focuses on:</p>
              <ul className="list-disc list-inside text-slate-600 text-sm space-y-1 ml-4">
                <li>The way the story itself talks about people and groups (not just what a bigoted character says)</li>
                <li>Patterns across the whole manuscript – who gets agency, who is described in what terms, and which 
                    details are highlighted or repeated</li>
              </ul>
              <p className="text-slate-700 text-sm mt-3 italic">
                Characters can be biased and flawed. The question Base44 helps with is: Does the narration quietly 
                agree with them, or challenge them?
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-slate-900 mb-2">How Base44 looks for inclusivity and bias</h3>
              <p className="text-slate-600 text-sm mb-2">
                Base44 scans your manuscript for signals that often show up in unconscious bias and exclusion:
              </p>
              <div className="space-y-2 ml-4">
                <div>
                  <p className="font-medium text-slate-800 text-sm">Loaded labels and descriptions</p>
                  <p className="text-slate-600 text-xs">
                    Repeated use of outdated or stigmatizing terms in narration (for race, gender, disability, age, etc.), 
                    especially when those labels are the main way a character is defined.
                  </p>
                </div>
                <div>
                  <p className="font-medium text-slate-800 text-sm">Tropes and patterns, not one-off lines</p>
                  <p className="text-slate-600 text-xs">
                    For example, if every disabled character is tragic, every fat character is a joke, or every woman 
                    is secondary and passive, Base44 will point out the pattern instead of any single sentence.
                  </p>
                </div>
                <div>
                  <p className="font-medium text-slate-800 text-sm">Unnecessary emphasis on identity</p>
                  <p className="text-slate-600 text-xs">
                    Moments where race, gender, religion, or disability is mentioned even when it isn't relevant to 
                    the scene, or only ever mentioned for certain groups.
                  </p>
                </div>
                <div>
                  <p className="font-medium text-slate-800 text-sm">Dehumanizing or distancing phrasing</p>
                  <p className="text-slate-600 text-xs">
                    Phrases that turn people into categories ("the illegals", "the crazies") or that describe groups 
                    as problems to be managed rather than people.
                  </p>
                </div>
              </div>
            </div>

            <div>
              <h3 className="font-semibold text-slate-900 mb-2">What you get back</h3>
              <p className="text-slate-600 text-sm mb-2">
                When Base44 sees possible bias in the narrative voice, it gives you:
              </p>
              <ul className="list-disc list-inside text-slate-600 text-sm space-y-1 ml-4">
                <li><strong>A neutral observation, not an accusation.</strong> Example: "Across 18 chapters, every police 
                    officer is described as corrupt or brutal, and no counterexamples appear."</li>
                <li><strong>A quick explanation</strong> of why some readers might read this as biased or stereotypical. 
                    Example: "Linking mental illness only to villainy can reinforce harmful stereotypes."</li>
                <li><strong>A specific, optional craft suggestion.</strong> Examples: Add one or two characters who break 
                    the pattern; Shift a judgment from the narrator into a character's interiority; Swap a label for 
                    person-first or identity-respecting language where that matches your intent.</li>
              </ul>
              <p className="text-slate-700 text-sm mt-3 font-medium">
                You are always free to ignore a suggestion if it conflicts with your artistic goals.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Checklist Download */}
        <Card className="mb-8 bg-gradient-to-br from-purple-50 to-indigo-50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Download className="w-5 h-5 text-indigo-600" />
              Inclusivity Review Checklist
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-slate-600 text-sm mb-4">
              Use this checklist when reviewing Base44's inclusivity notes. Answer these questions in the margin or in a notebook.
            </p>

            <div className="space-y-4 mb-6">
              <div className="border-l-4 border-l-indigo-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">1. Intent and necessity</h3>
                <ul className="text-sm text-slate-600 space-y-1">
                  <li>□ Does this line/description clearly serve a story purpose (characterization, conflict, theme), or is it just habit or cheap shorthand?</li>
                  <li>□ If a stranger read this sentence with no context, what would they reasonably think it says about the group mentioned?</li>
                  <li>□ Could the same effect be achieved without leaning on identity (race, gender, disability, etc.) at all?</li>
                </ul>
              </div>

              <div className="border-l-4 border-l-purple-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">2. Point of view and ownership</h3>
                <ul className="text-sm text-slate-600 space-y-1">
                  <li>□ Whose voice is this: the character's, or the narrator's?</li>
                  <li>□ If it is the narrator, does this language reflect your view, or is it accidentally echoing a biased character?</li>
                  <li>□ Is this identity being written from the inside (lived experience / deep research) or the outside? If outside, have you been specific and respectful enough?</li>
                </ul>
              </div>

              <div className="border-l-4 border-l-pink-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">3. Patterns, not one-offs</h3>
                <ul className="text-sm text-slate-600 space-y-1">
                  <li>□ Looking across the chapter or book, does this group mostly appear in one role (victim, villain, comic relief, helper, love interest)?</li>
                  <li>□ Are certain adjectives or labels only ever applied to one group (e.g., "sassy", "exotic", "crazy", "illegal")?</li>
                  <li>□ If you swapped the group for another, would the pattern suddenly look obviously biased or clichéd?</li>
                </ul>
              </div>

              <div className="border-l-4 border-l-blue-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">4. Language choices and labels</h3>
                <ul className="text-sm text-slate-600 space-y-1">
                  <li>□ Am I using any terms that current inclusive-language guides flag as outdated, dehumanizing, or stigmatizing? (e.g., "the disabled", "illegals", "crazy people")</li>
                  <li>□ Is identity mentioned only when it's relevant, or am I calling out race, gender, or disability where I wouldn't for a default/dominant group?</li>
                  <li>□ Can I swap a label for a more precise or person-first phrasing without losing power? (e.g., "disabled people" or "people with X" vs "the X")</li>
                </ul>
              </div>

              <div className="border-l-4 border-l-green-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">5. Impact on real readers</h3>
                <ul className="text-sm text-slate-600 space-y-1">
                  <li>□ If a reader who shares this identity saw only this representation, how might it land: seen, stereotyped, erased, or used as a prop?</li>
                  <li>□ Does this joke/description punch down at people with less power, or punch up at systems and structures?</li>
                  <li>□ If someone flagged this line in a review or sensitivity read, could you clearly explain why you chose it and what you were trying to do?</li>
                </ul>
              </div>

              <div className="border-l-4 border-l-amber-500 pl-4">
                <h3 className="font-semibold text-slate-900 mb-2">6. Revision decisions</h3>
                <p className="text-sm text-slate-600 mb-2">For each flagged instance, note:</p>
                <ul className="text-sm text-slate-600 space-y-1">
                  <li>□ Am I keeping this as-is because it's essential to character or theme?</li>
                  <li>□ Am I tweaking wording or context to reduce collateral harm while keeping the same dramatic function?</li>
                  <li>□ Am I replacing or cutting because it's lazy shorthand, cliché, or not worth the cost?</li>
                </ul>
                <p className="text-sm text-slate-700 mt-3 font-medium italic">
                  If you consistently answer "I'm not sure": Mark those spots for discussion with a trusted beta reader, editor, or sensitivity reader who shares (or deeply knows) the identity in question.
                </p>
              </div>
            </div>

            <Button onClick={handleDownloadChecklist} className="bg-indigo-600 hover:bg-indigo-700">
              <Download className="w-4 h-4 mr-2" />
              Download as Text File
            </Button>
          </CardContent>
        </Card>

        {/* For Professionals Box */}
        <Card className="mb-8 border-2 border-blue-200 bg-blue-50/50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-blue-900">
              <Users className="w-5 h-5" />
              For agents, editors, and publishers
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-blue-900">
              Base44's annotations help surface potential content concerns early, making it easier to discuss intent, 
              market fit, and risk before submission or acquisition. This system doesn't replace sensitivity readers 
              or editorial judgment—it augments your workflow by catching patterns that might otherwise emerge only 
              after advance copies circulate.
            </p>
          </CardContent>
        </Card>

        {/* Summary Callout */}
        <Card className="mb-8 border-2 border-indigo-300 bg-gradient-to-br from-indigo-50 to-purple-50">
          <CardContent className="p-6 text-center">
            <p className="text-xl font-semibold text-slate-900 mb-2">
              In short: Base44 doesn't tell you what to write.
            </p>
            <p className="text-lg text-slate-700">
              It helps you understand how what you've written may be read.
            </p>
          </CardContent>
        </Card>

        {/* Positioning Statement */}
        <Card className="border-l-4 border-l-indigo-500">
          <CardContent className="p-6">
            <p className="text-slate-700 text-lg font-medium">
              We believe authors should be able to write difficult, uncomfortable, and morally complex stories—without 
              being blindsided later by platform rules or reader backlash.
            </p>
            <p className="text-slate-600 text-sm mt-3">
              Base44 makes risk visible so you can make informed choices about your creative work.
            </p>
          </CardContent>
        </Card>

        {/* Cross-links */}
        <div className="mt-8 grid grid-cols-2 gap-4">
          <Link to={createPageUrl('SlurHandlingPolicy')}>
            <Card className="hover:shadow-md transition-shadow cursor-pointer border-2 border-slate-200 h-full">
              <CardContent className="p-4">
                <h3 className="font-semibold text-slate-900 mb-1">Technical Policy</h3>
                <p className="text-xs text-slate-600">
                  View the detailed slur handling policy document
                </p>
              </CardContent>
            </Card>
          </Link>
          <Link to={createPageUrl('FAQ')}>
            <Card className="hover:shadow-md transition-shadow cursor-pointer border-2 border-slate-200 h-full">
              <CardContent className="p-4">
                <h3 className="font-semibold text-slate-900 mb-1">FAQ</h3>
                <p className="text-xs text-slate-600">
                  Common questions about how Base44 works
                </p>
              </CardContent>
            </Card>
          </Link>
        </div>
      </div>
    </div>
  );
}