import React from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, Film, Download } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';

export default function SampleFilmPitchDeck() {
    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50">
            <div className="max-w-4xl mx-auto px-6 py-12">
                {/* Back Button */}
                <Link to={createPageUrl('SampleAnalyses')}>
                    <Button variant="ghost" className="mb-6">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back to Sample Analyses
                    </Button>
                </Link>

                {/* Header */}
                <div className="mb-8">
                    <div className="flex items-center gap-3 mb-4">
                        <div className="p-3 rounded-xl bg-gradient-to-br from-pink-500 to-purple-600">
                            <Film className="w-6 h-6 text-white" />
                        </div>
                        <div>
                            <h1 className="text-3xl font-bold text-slate-900">Film Adaptation Pitch Deck</h1>
                            <p className="text-slate-600 mt-1">Cartel Babies</p>
                        </div>
                    </div>
                    <Badge className="bg-pink-100 text-pink-700 border-pink-200">
                        Sample Screenplay Analysis
                    </Badge>
                </div>

                {/* Context Banner */}
                <Card className="mb-8 border-l-4 border-l-indigo-500">
                    <CardContent className="pt-6">
                        <p className="text-sm text-slate-700 leading-relaxed">
                            This is a <strong>sample film pitch deck</strong> generated by RevisionGrade's Film Adaptation Package. 
                            It demonstrates the platform's ability to analyze manuscripts/screenplays for screen viability, 
                            generate structured pitch content, and provide producer-ready analysis across 12 key slides.
                        </p>
                    </CardContent>
                </Card>

                {/* Screen Viability Score */}
                <Card className="mb-8 bg-gradient-to-br from-slate-900 to-indigo-900 border-0">
                    <CardContent className="pt-6">
                        <div className="flex items-center justify-between mb-4">
                            <div>
                                <h2 className="text-2xl font-bold text-white mb-2">Screen Viability Score</h2>
                                <p className="text-indigo-200 text-sm">Producer Assessment</p>
                            </div>
                            <div className="text-right">
                                <span className="text-5xl font-bold text-emerald-400">8.5</span>
                                <span className="text-white/60 text-xl">/10</span>
                            </div>
                        </div>
                        <p className="text-white/90 leading-relaxed">
                            Cartel Babies presents a compelling, high-concept literary thriller with a deeply emotional, character-driven core. 
                            The dual-protagonist structure offers a unique narrative engine, blending a tense survival story with a heart-wrenching 
                            emotional journey. The character of Raúl is a standout, providing a complex, awards-caliber role for a top-tier actor. 
                            While the dense backstory will require skillful adaptation to maintain pacing in a feature format, the material is 
                            exceptionally well-suited for a premium limited series. The project's primary strengths are its powerful found-family theme, 
                            its visually rich setting, and its potent blend of commercial thriller elements with prestige drama, giving it strong appeal 
                            in both domestic and international markets.
                        </p>
                    </CardContent>
                </Card>

                {/* Pitch Deck Slides */}
                <div className="space-y-6">
                    {[
                        {
                            number: 1,
                            title: "Title Slide",
                            content: "Title: Cartel Babies. Tagline: In Sinaloa, survival is a negotiation. Family is the price. Genre: Literary Thriller / Character-Driven Crime Drama."
                        },
                        {
                            number: 2,
                            title: "Logline",
                            content: "A pragmatic Canadian man, abducted by a Sinaloan cartel, must navigate a brutal hierarchy and forge an unlikely alliance with a conflicted capo to save the man's young son and escape a world that consumes everyone it touches."
                        },
                        {
                            number: 3,
                            title: "Synopsis",
                            content: "When a routine drive in Sinaloa turns into a violent kidnapping, 68-year-old Canadian Michael Meraw is plunged into the brutal world of a cartel meth camp. Stripped of his identity, he uses his quiet resilience to survive, forming an unexpected bond with the camp leader's young son, Paolito, over a makeshift game of table tennis. While Michael fights for his life, his partner, Benjamin, begins a desperate search in Culiacán. Battling indifferent authorities and his own internal demons, Benjamin's journey transforms him from a timid student into a resourceful man willing to risk everything. As a violent cartel power struggle provides a narrow window for escape, Michael must honor a pact with the conflicted capo, Raúl, to save Paolito. This culminates in a harrowing escape and a reunion in Canada, where the three must learn to build a new family from the ashes of trauma."
                        },
                        {
                            number: 4,
                            title: "Protagonists",
                            content: "MICHAEL MERAW (60s): A retired Canadian pilot with a deceptively calm demeanor and a hidden core of resilience. Abducted and stripped of his identity, his arc is not about becoming an action hero, but about rediscovering his purpose as a protector. BENJAMIN ESPINOZA (20s): Michael's anxious, self-conscious partner. His journey is the film's emotional heart. Michael's disappearance forces him to confront his fears, evolving from a dependent young man into a courageous and resourceful partner. STAKES: For Michael, it's immediate survival and the moral weight of protecting a child. For Benjamin, it's losing the only person who ever saw him for who he truly is."
                        },
                        {
                            number: 5,
                            title: "Antagonist & Conflict",
                            content: "THE CARTEL SYSTEM: The primary antagonist is the dehumanizing machine of the cartel, a world of shifting loyalties and casual violence, personified by the brutal enforcer El Tomatero. RAÚL MADERA (30s): A complex, 'sympathetic' antagonist. As the camp capo and Paolito's father, he is both captor and protector. His internal conflict—torn between cartel duty and his love for his son—drives the central drama. INTERNAL CONFLICT: Michael battles despair and the temptation to remain a detached observer, while Benjamin fights crippling anxiety and the shame instilled by his family. Both must overcome their internal limitations to act."
                        },
                        {
                            number: 6,
                            title: "World & Setting",
                            content: "A TALE OF TWO SINALOAS: The film contrasts the dusty, sun-bleached brutality of the Sierra Madre meth camp with the vibrant, tense urban sprawl of Culiacán. This visual dichotomy highlights the parallel worlds of captivity and a fragile, fraught freedom. VISUAL TONE: A blend of the raw, grounded realism of 'Sicario' with the poetic, character-focused intimacy of 'Amores Perros'. The camp is a world of claustrophobic canvas, harsh light, and chemical haze. Culiacán is bright and loud, but carries an undercurrent of menace. INSPIRATION: The stark, beautiful landscapes of Denis Villeneuve meet the character-centric grit of Alejandro González Iñárritu. The world is a character—beautiful, unforgiving, and steeped in violence."
                        },
                        {
                            number: 7,
                            title: "Themes",
                            content: "FOUND FAMILY: The core theme is the creation of family in the most unlikely of circumstances. The bond between Michael, Benjamin, and Paolito forms a non-traditional family unit forged in trauma, challenging conventional notions of fatherhood and partnership. THE PRICE OF SURVIVAL: The story explores the moral compromises and psychological scars required to endure extreme circumstances, asking if one can survive a brutal system without becoming part of it. QUIET RESISTANCE VS. LOUD VIOLENCE: The film contrasts the overt brutality of cartel enforcers with Michael's quiet resistance—observation, strategy, and empathy. His greatest weapon isn't a gun; it's his ability to see the humanity in his captors and turn it into a lifeline."
                        },
                        {
                            number: 8,
                            title: "5-Part Mythic Structure",
                            content: "ORDINARY WORLD: Michael lives a quiet, low-profile life in Mexico with his partner Benjamin, who struggles with family expectations and self-doubt. THE DESCENT: Michael is abducted, thrusting him into the brutal reality of the cartel camp. For Benjamin, the call is Michael's sudden, terrifying silence. TRIALS & ALLIANCES: Michael survives by forging a bond with Paolito and a complex alliance with Raúl. Benjamin faces his own trials: navigating a corrupt system and confronting his family's judgment. CLIMAX: A violent cartel power shift provides a narrow 'window' for escape. Michael must choose between saving himself or honoring his pact to save Paolito, culminating in a harrowing escape from the compromised camp. RESOLUTION: Michael and Paolito are reunited with Benjamin in Canada. Scarred but together, they form a new family unit, the 'elixir' being the hard-won bonds of love and loyalty."
                        },
                        {
                            number: 9,
                            title: "Visual Style",
                            content: "CINEMATOGRAPHY: Handheld, intimate camerawork for Benjamin's frantic search in Culiacán, creating anxiety and immediacy. In contrast, the camp scenes will use static, observational shots, emphasizing Michael's feeling of being trapped and watched. COLOR PALETTE: The camp is defined by desaturated earth tones—dusty browns, bleached greens—punctuated by startling flashes of color (Paolito's red jersey, El Tomatero's truck). Culiacán is vibrant but unsettling. LIGHTING: Harsh, unforgiving natural light in the camp contrasts with the neon-soaked nights of Culiacán, creating a visual language that reflects the characters' internal states."
                        },
                        {
                            number: 10,
                            title: "Tone & Comp Titles",
                            content: "TONE: A grounded, emotionally resonant thriller. The film balances moments of visceral tension with profound, quiet character intimacy. It is unflinching in its depiction of violence but never gratuitous—the focus is always on the human cost. COMPARABLE FILMS: 'Sicario' (visual style, cartel realism), 'Amores Perros' (character-driven storytelling in Mexico), 'No Country for Old Men' (moral ambiguity, quiet tension), 'Hell or High Water' (themes of loyalty, survival, and found family). TARGET AUDIENCE: Fans of intelligent thrillers, prestige crime dramas, and character-driven narratives. Appeals to both arthouse and commercial audiences."
                        },
                        {
                            number: 11,
                            title: "Commercial Appeal",
                            content: "DOMESTIC BOX OFFICE: Strong potential as a mid-budget prestige thriller, appealing to adult audiences seeking intelligent, emotionally resonant stories. INTERNATIONAL MARKET: Exceptionally strong. The Mexican setting, bilingual dialogue, and universal themes of family and survival will resonate globally, particularly in Latin America and Europe. STREAMING POTENTIAL: Ideal for a premium limited series format, allowing for deeper character exploration and pacing. Platform potential: Netflix, HBO, Amazon. AWARDS TRAJECTORY: Multiple opportunities for acting nominations (Raúl, Michael, Benjamin), screenplay, and direction. Strong contender for festival circuit recognition."
                        },
                        {
                            number: 12,
                            title: "Why This Story Now",
                            content: "CULTURAL RELEVANCE: In an era of increasing migration, border politics, and global awareness of cartel violence, 'Cartel Babies' offers a deeply human perspective on a fraught reality. It challenges stereotypes, presenting Mexican characters with depth and agency. REPRESENTATION: The film centers a queer relationship in a genre often dominated by heteronormative narratives, offering authentic LGBTQ+ representation without making it the sole focus of the story. EMOTIONAL URGENCY: Post-pandemic audiences are seeking stories that explore resilience, trauma, and the creation of chosen families. This story delivers that with unflinching honesty and emotional depth."
                        }
                    ].map((slide) => (
                        <Card key={slide.number} className="border-0 shadow-lg">
                            <CardHeader>
                                <div className="flex items-center gap-3">
                                    <div className="flex items-center justify-center w-10 h-10 rounded-full bg-indigo-100 text-indigo-700 font-bold">
                                        {slide.number}
                                    </div>
                                    <CardTitle className="text-lg">{slide.title}</CardTitle>
                                </div>
                            </CardHeader>
                            <CardContent>
                                <p className="text-slate-700 leading-relaxed whitespace-pre-line">{slide.content}</p>
                            </CardContent>
                        </Card>
                    ))}
                </div>

                {/* Purpose Statement */}
                <Card className="mt-8 border-l-4 border-l-amber-500 bg-amber-50">
                    <CardContent className="pt-6">
                        <h3 className="font-semibold text-slate-900 mb-2">Purpose of This Sample</h3>
                        <p className="text-sm text-slate-700 leading-relaxed">
                            This sample demonstrates RevisionGrade's <strong>Film Adaptation Package</strong>: a structured, 
                            producer-ready pitch deck that translates manuscript content into screen-viable analysis. 
                            The deck includes logline, synopsis, character breakdowns, thematic analysis, visual style guidance, 
                            comparable titles, and commercial viability assessment—all calibrated against industry standards.
                        </p>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}